### ISSUE TITLE
Make the proto type in the `Protobuf` trait an associated type

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1021]
**Is your feature request related to a problem? Please describe.**

We've talked about adding an object cache to the `State`, so that compound objects (like a `CompactBlock`) can be built up incrementally, without constant serialization round-trips.  This would basically involve having a `HashMap<KeyHash, Box<dyn Protobuf>>`, but we can't do that right now, because the `Protobuf` type has a type parameter, so we can't have a collection of "some kind of domain type" without naming the proto type.

**Describe the solution you'd like**

Redo #353 at some point soon when there are no in-flight changes to the codebase (since it will conflict with basically everything).

**Comment by plaidfinch** [comment]
I don't think redoing #353 will actually solve this, because `dyn Trait` requires you to specify the associated type, too. For example ([check it out in the Rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=fbc94a3109123c7ffe083912e4dbe688)):

```rust
trait Trait {
    type Associated;
}

struct Struct;

impl Trait for Struct {
    type Associated = ();
}

type DynTrait = dyn Trait;
```

This results in the error:

```
error[[E0191]](https://doc.rust-lang.org/stable/error-index.html#E0191): the value of the associated type `Associated` (from trait `Trait`) must be specified
  --> src/lib.rs:11:21
   |
2  |     type Associated;
   |     ---------------- `Associated` defined here
...
11 | type DynTrait = dyn Trait;
   |                     ^^^^^ help: specify the associated type: `Trait<Associated = Type>`

For more information about this error, try `rustc --explain E0191`.
```

In some sense, the rust compiler treats associated types as "function-like type parameters", and they inherit the `dyn` restriction of needing to be specified. The reason this restriction exists is that if you added a method like `fn get() -> Self::Associated`, this couldn't be called on a `dyn Trait` object without the type `Associated` being fixed, or else the calling convention would differ dynamically, which would be unsafe.

I think you're right that we need to implement #353, but then additionally we also need to make an extension trait which which is both `dyn`-safe and does not require us to specify the associated type. This would look something like (assuming `Protobuf` has an associated type `Proto` instead of its current unfixed generic type):

```rust
trait CacheObject: Any {
    fn encode(&self) -> Vec<u8>;
    fn decode(buffer: &[u8]) -> anyhow::Result<Self>; // has to be monomorphic to be dyn-safe
}

impl<T: Protobuf + Any> CacheObject for T {
    fn encode(&self) -> Vec<u8> {
        <Self as Protobuf>::encode_to_vec(self)
    }
    
    fn decode(buffer: &[u8]) -> anyhow::Result<Self> {
        <Self as Protobuf>::decode(buffer)
    }
}
```

Then we could have our cache be a `HashMap<KeyHash, Box<dyn CacheObject>>`.

It's also worth noting that since `KeyHash`es are already hashed, we would benefit by using `hash_hasher`'s `HashedMap`, which is a much faster hash than the default hash map hash, provided that the input is already hashed.

**Comment by hdevalence** [comment]
Thanks for writing this up, this is really helpful to flag before we dive in to making changes.

My sense from this is that we should pause on making big changes to the traits, make a new issue to discuss the changes to the `State` design, and then figure out whether the benefit of implementing that is currently worth it relative to everything else.

**Comment by plaidfinch** [comment]
An update on this comment:

> It's also worth noting that since `KeyHash`es are already hashed, we would benefit by using `hash_hasher`'s `HashedMap`, which is a much faster hash than the default hash map hash, provided that the input is already hashed.

The newer state architecture has this be a `BTreeMap<String, Option<Vec<u8>>>`, so the commentary about `hash_hasher` no longer is applicable.

**Comment by plaidfinch** [comment]
Further thoughts: I think the solution proposed above is actually not right. The signature of `CacheObject::decode` still varies by the type of `T`, which means that `CacheObject` isn't `dyn`-safe after all, since if `T` differed, then the return type of that method would, which would be a memory safety violation. We need to add a `where Self: Sized` bound to `decode`, which means that it can only be invoked on a known `T` (this is also, already true, because it's a static method). Because of this restriction, we can also allow `decode` to be fully polymorphic again:

```rust
trait CacheObject: Any {
    fn encode(&self) -> Vec<u8>;
    fn decode<B: bytes::Buf>(buf: B) -> anyhow::Result<Self> where Self: Sized;
}
```

In the RYW cache, we only need to invoke `encode` on `Box<dyn CacheObject>`s, to write them out; reading things into the cache from disk is not done. So we could also drop the method entirely.

**Comment by hdevalence** [comment]
In the end, we decided not to do this, and instead we have an object cache as part of the state.
