### ISSUE TITLE
Pay out fees to validator funding streams

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#1067]
Fees paid are currently burned, but they should instead accrue to validator funding streams, to incentivize a market on block space.

**Comment by plaidfinch** [comment]
How can a validator sort transactions by fee in order to preferentially include the highest-fee ones?

**Comment by hdevalence** [comment]
> How can a validator sort transactions by fee in order to preferentially include the highest-fee ones?

We don't actually need to do anything here, since block proposal is outside of consensus — validators can run custom software, or have someone else build the block for them ("proposer/builder separation").

Actually I'm not even sure we need to do anything here, the fact that fees are burned still creates an incentive for validators to prefer higher-fee transactions (since burning tokens is equivalent to paying every other token holder pro rata to their holdings).

**Comment by hdevalence** [comment]
Closed in favor of #1224
