### ISSUE TITLE
view service: also scan for outgoing transactions

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#1101]
After #1075, we'll be able to detect our outgoing transactions.

This means we should update the view service to attempt to decrypt the `ovk_wrapped_key` field in each `OutputBody` using our `OutgoingViewingKey`. If we're able to decrypt, then it means we can decrypt the `NotePayload` (and optionally the `Memo`) using the decrypted key material.

**Comment by hdevalence** [comment]
Instead of doing this, we detect outgoing transactions statefully, by matching against the nullifiers we know we control.  The current code will already download full transaction contents of transactions that spend funds (by checking nullifiers) as well as transactions that receive funds (by checking note sources).
