### ISSUE TITLE
`EditProposal` action

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#1149]

**Comment by hdevalence** [comment]
We should strongly consider not doing this -- it's unclear how big the benefit is, and adds an enormous amount of complexity, both in the implementation (the fact that we have to implement it at all, how it interacts with other parts of the system, how do we correctly track updates to proposal states, etc), and in the social dynamics (what does it mean that it's possible to edit a proposal while voting is ongoing, what happens if someone completely rewrites the proposal right before the vote closes, etc).

**Comment by plaidfinch** [comment]
I had meant to close this issue after previous discussion; it's already been removed from the tracking issues, I just missed closing the issue itself.
