### ISSUE TITLE
Should the DAO have an address?

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#1229]
Some validators might desire to allocate some of their funding streams to the DAO itself. Currently this isn't possible because the DAO account doesn't have an address. If we added a specially designated address for the DAO, it would be possible, as well as allowing perhaps a simpler interface to sending to the DAO.

Some suggestions:

- The all-zero address?
- `penumbrav1tDAO`?

The representation of the `Address` type should then become an `enum` with a special case for the DAO.

Alternatively, we could add a DAO case only to funding streams, rather than to the `Address` itself.

**Comment by hdevalence** [comment]
> Currently this isn't possible because the DAO account doesn't have an address.

It's not possible for a bigger reason than that, which is that the funding stream mechanism relies on creating notes, which relies on being able to have an address with the normal key hierarchy.  The point of the community pool is to not have any key material, but the existing address structure relies on end-user key management (which is a necessary component of having privacy; if there's no key material, there's no way to have on-chain privacy).  That's why we have to have a special `DaoDeposit` action, rather than a shielded `Output` action.

Adding a specially designated "address" (encoding) for the community pool / dao treasury doesn't change this mismatch.  If we want to allow validators to dedicate funding streams to the community pool, we could either (1) change the definition of the funding stream to have a community pool case or (2) have validators commit off-chain to transferring funds (e.g., by publishing the viewing key for the address that they intend to redirect to the community pool).

I think we should go towards (2) for now ("do nothing").
