### ISSUE TITLE
specify how to handle bridged assets that won't fit in a u64

### ISSUE THREAD

**Issue by avahowell** [penumbra-zone/penumbra#1336]
Currently, Penumbra implements notes with amounts as a `u64`. This works well for native assets, however some bridged assets (such as those originating on Ethereum) may have high enough decimals that they will not fit in a single `u64`. 

Additionally, the [ICS-20](https://github.com/cosmos/ibc/tree/main/spec/app/ics-020-fungible-token-transfer) spec specifies a FungibleTokenPacketData as follows:

```
interface FungibleTokenPacketData {
  denom: string
  amount: uint256
  sender: string
  receiver: string
}
```

Note that the amount is given as a u256.

We should decide how we handle bridged assets with an `amount` greater than what we can fit in Penumbra's notes. A few approaches come to mind:

1. Reject all bridge assets with a total supply that won't fit in a u64. With tokens with high decimal precision, such as 18 decimal Ethereum assets, this limits total supply to an unacceptably small amount.
2. Change the size of penumbra notes to u128. This can be done in conjunction with 1), which would greatly raise the total limits for those assets.

cc @hdevalence @plaidfinch @aubrika

**Comment by redshiftzero** [comment]
### Impacts of moving to u128 notes

The size of note plaintexts and ciphertexts will increase by 8 bytes. This is negligible compared to their current size: 152 bytes and 168 bytes respectively. 

This means that outputs increase in size by 8 bytes. Transactions overall increase in size by 8 bytes if they use the u128 amount type for fees.

For the current implementation of swaps where we include the values in plaintext:
* adds 8 bytes per asset, so 16 bytes,
* another 8 bytes for the increase in the note that’s included in the swap,

That’s an additional 24 bytes per swap. When we move from our current implementation without flow encryption to using flow encryption, we’ll be using the value commitments in the swaps instead of the values, in which case there’d be only an 8 byte increase (due to the note) relative to u64 notes.

For the current implementation of swap claims, we’d have another increase in 24 bytes in the size of swap claims:
* 8 bytes extra for the `Fee`
* 8 bytes each for the two output notes = 8 * 2

For our protos, there is no uint128 type, so we could:
* Add an amount proto type which we'd use for the amount fields of the `Value` (used by `Note`s and `Fee`s)
* Inside it will have two fields of uint64, one for the lower bits, one for the upper bits (or one field with some other custom encoding?).

Otherwise in the rest of the codebase we would use the Rust u128 type.

For ZK proofs, our range checks will be over 128 bits instead of 64 for amounts. Otherwise the rest of the proof logic should be unchanged (for the transparent proofs we don’t care about the implications since they’re not for production use).
