### ISSUE TITLE
`pcli` doesn't handle ephemeral address indexes correctly

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1393]
**Describe the bug**

`pcli` gets kind of borked when the view service has a note that was sent to an ephemeral address, because there are various places in the code where it's assumed that address indexes are always numeric.

Examples:

- `pcli view balance --by-address` will display 128-bit address indexes, as if they were integers, but those integers can't be plugged in as a source address
- When swap claims were output to an ephemeral address, they broke the spend planner, because it barfed on seeing a note with a non-numeric address index.

We should figure out how we want to deal with this.  Currently, pcli's `source_address` feature is a way to use addresses as pseudo-accounts. This seems useful, because it allows having multiple accounts (for accounting purposes) without having to do extra scanning work. Do we want to have any way for the CLI to distinguish between different ephemeral addresses, or should it treat "all ephemeral addresses" as a single pseudo-account?

**Comment by plaidfinch** [comment]
The second bullet point is outdated, right?

**Comment by mikayla-maki** [comment]
Talked with @plaidfinch about tackling this today and evaluated the two solutions:
- Collapsing down all ephemeral transactions to one ephemeral account. This might have a usability issue as users might want to know the actual address for each ephemeral account in order to confirm that they received a trade properly.
- Expanding the table to show the associated index, with a placeholder for ephemeral addresses, and an addresses prefix. This might also have usability problems for people who have a large number of external transactions. Most of the addresses would just be noise.

**Comment by hdevalence** [comment]
What's the concern with collapsing all of the ephemeral addresses into one row? We'll still be able to list off individual transactions, or display individual note balances, so a user can confirm specific transactions if they want.

I think we want to logically group all of the ephemeral addresses, rather than support their being treated separately, because we already have a mechanism to allow users to track activity on a per-address basis, namely, by using indexed addresses.

**Comment by mikayla-maki** [comment]
Good point on how displaying transactions covers that use case. I’ll focus on treating all ephemeral addresses as one address then :D
