### ISSUE TITLE
`pd`: determine how to handle failed `DeliverTx`

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#145]
If a malicious proposer proposes a block with invalid transactions, then we will learn about it through `DeliverTx`. This issue is to determine what we should do on the ABCI side, I'm guessing that we should store some data perhaps on `PendingBlock` or somewhere else and slash the misbehaving block proposer during `EndBlock`. 

Relevant upstream conversations: 
https://github.com/tendermint/tendermint/issues/2175
https://github.com/tendermint/tendermint/issues/2384

**Comment by hdevalence** [comment]
xref https://github.com/informalsystems/tendermint-rs/pull/862#discussion_r739563652

**Comment by redshiftzero** [comment]
There are two related questions/concerns, both will need handling:
1. How do we prevent committing invalid transactions in the case of a malicious proposer? (e.g. by using ABCI++)
2. How should we punish malicious proposers that propose blocks with invalid transactions? (this is something we can currently do on the application side since we get the non-zero code returned by `DeliverTx` as described above)

**Comment by hdevalence** [comment]
When we switch to ABCI++, we can have the application not vote for proposed blocks with invalid transactions.

Until then, we should take care in `DeliverTx` (#135) to check every transaction in the block carefully, and ignore any invalid ones (i.e., a malicious proposer can include garbage transactions, but the consensus state will ignore them, so they have no reason to do so).

I don't think we need to handle punishment of malicious proposers, because we'll switch to ABCI++ before deploying something real.
