### ISSUE TITLE
Add option to funding stream to allow sending directly to the DAO

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#1451]

**Comment by hdevalence** [comment]
Since the DAO account is special, and does not have an address, we probably want to do this by changing the `FundingStreams` from a `Vec<FundingStream>` to a `Vec<FundingStream>` plus a `dao_contribution`. We could do this in advance of implementing the DAO treasury (by burning the contribution), but it seems better to wait until we actually have an account to record funds in.

**Comment by hdevalence** [comment]
Closed by #1802
