### ISSUE TITLE
Refactor MemoPlaintext to be a fixed-length String

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#1510]
This touches enough of the codebase to deserve its own tracking issue: MemoPlaintext is used in several places but we would be better served by a fixed-length string, though swapping it out may take some thinking about how best to refactor the functions on the implementation.

**Comment by conorsch** [comment]
> we would be better served by a fixed-length string

Can someone elaborate on the utility of switching to a string and ditching the struct entirely? I can see that a string would be more pleasant to work with than a vec, but having the methods bundled to the struct for encrypt/decrypt actions strikes me as a pleasant convenience. If anything, I'm biased toward leveraging the `impl` further: we currently validate that the memo text is less than `MEMO_LEN_BYTES` in several places, but it might be safer to move that validation logic into a constructor, so that future maintainers don't overlook it when using memos elsewhere.

**Comment by zbuc** [comment]
The intent is to make sure the memo is UTF-8 encoded, so really what we are looking for is a fixed-length UTF-8 string

**Comment by hdevalence** [comment]
> I can see that a string would be more pleasant to work with than a vec, but having the methods bundled to the struct for encrypt/decrypt actions strikes me as a pleasant convenience.

One point here is that, ideally, users of these APIs won't be calling encrypt/decrypt directly: when creating a transaction, they would construct a `TransactionPlan` with the `Planner` API, then call `build` (which would do encryption internally), and when viewing a transaction, they'd use a `TransactionPerspective` to create a `TransactionView`, which provides an already decrypted and "interpreted" view of the transaction.

In either of those cases, an API user will just be operating on the plaintext of the transaction, and at that point, having a `String` is much more ergonomic.

We also don't necessarily need or want the string to be fixed-length.  For instance, if I create a transaction with the memo field `"for pizza"`, my 9-byte memo will be padded with 0s to get a fixed-length memo ciphertext. But when I look at the transaction later, I don't really want to see `"for pizza\0\0\0...(503 zeros)...\0"`, I just want to see `"for pizza"`.  Or, if I'm reviewing a `TransactionPlan` before signing, seeing the zero-padded memo plaintext isn't particularly helpful either.

So I think it's simplest just to treat the memo plaintext as an ordinary `String`.

Now we have two decisions to make:

1. How do we handle the conversion from variable-length `String`s to 512-byte plaintexts when building a transaction?
2. How do we handle the conversion from 512-byte plaintexts to UTF-8 `String`s when decrypting a memo?

On the first question, I think a reasonable answer is to pad an undersized input with `0` bytes, so we have a canonical padding.  For oversized inputs, we could either error or truncate.  Erroring is probably safer, and `TransactionPlan::build` is already fallible. We'll also want to change the `Planner` API so that the `Planner::memo` method is fallible.

The second question relates to @zbuc's point:

It is unsafe to assume the string is UTF-8 when decoding, and the error must be handled gracefully to prevent crashing the view service with malicious transactions.

Not only is it difficult to prove, but also, we don't prove anything about the note or memo plaintexts at all.  The ZK validity checks are only applied to the note commitments, and the `NotePayload` containing the symmetrically encrypted plaintext is treated as an in-band messaging system between the sender and the receiver. The assumption is that if the sender constructs a malformed plaintext, the receiver simply doesn't agree that a payment happened.

**Comment by conorsch** [comment]
The PR at https://github.com/penumbra-zone/penumbra/pull/1548 is almost ready, and functionally seems sound. I'm going to keep this issue open post-merge to ensure that adequate testing, such as via [proptest](https://altsysrq.github.io/proptest-book/intro.html), is added, possibly after the next testnet.
