### ISSUE TITLE
switch to `sqlx::query_as!` and `sqlx::query!` macros

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#155]
We've recently hit two similar bugs (https://github.com/penumbra-zone/penumbra/issues/154 being the most recent) that @kwf pointed out we could be catching at build time if we were using the `sql::query!` and `sql::query_as!` macros instead of the corresponding functions.

This issue is to take a pass through the current codebase and switch to the macros. 

It does mean that a database connection will be required at build time, and in offline mode (i.e. CI) we'll need to check in a JSON file containing our database details: https://docs.rs/sqlx/0.5.9/sqlx/macro.query.html#offline-mode-requires-the-offline-feature

**Comment by hdevalence** [comment]
If we do this, we should use the "offline mode" by default so that we do not require a database connection at build time.  We should also ensure that the steps to rebuild the JSON file can be automated (maybe a `Makefile`?).  I think the easiest way would probably be to have something that uses `docker` to create a database instance, regenerates the JSON, and then shuts down & destroys the database.

Another improvement that touches the same code and could (potentially?) be done at the same time would be to switch to using prepared queries.  I'm not sure exactly how that works, but @kwf mentioned that their understanding is that the macros give this for free.

**Comment by kwf** [comment]
Another code-structuring improvement we might consider is using [`query_file!`](https://docs.rs/sqlx/0.5.9/sqlx/macro.query_file.html) to move the queries into separate files, which might make things a little cleaner.
