### ISSUE TITLE
Tokenize Quarantining

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#1581]
## The situation

Right now, we have a bespoke implementation of quarantining for undelegations which has a number of downsides:

1. It's complex, both on the node side (which would be fine, except...) and also this complexity bleeds over into client interface implementations. Clients need to track a whole separate Kind Of Thing which is an **un-**positioned quarantined `Note`, and correctly model the state change when a note becomes unquarantined. It's easy to get wrong (we have, several times, notably a write ordering causing #1507), and we don't want to impose this burden forever to penumbra client interface users.
2. It requires special guardrails to avoid accidentally making a randomly selected chunk of your notes temporarily illiquid: see #1010 for the solution to that. Every penumbra client would need to make sure they do this, or else risk a bug where they lock up unrelated user funds of unbounded amount until the unbonding period expires.
3. It works differently than the rest of the "zk-async" penumbra state model. We now know how to model things Of This Sort better, as we've done with swap/swap-claim: make a token representing the "future" you want to redeem, then make a second transaction to redeem it. This works for swaps, and it should work for quarantining (as well as governance proposal deposit refunds, to be discussed separately).

## A solution

Instead of our bespoke quarantining system, we should make new assets, here called **Unbonding Tokens** (bikeshed in the comments). Just as every validator is associated with precisely one Delegation Token asset, they would also be associated with a family of unbonding token denominations, parameterized by epoch. For example, the denomination `unbonding_epoch_12_until_15_penumbravalid1ymlgthzee7nzn7nhrz38u4p5a580uzdupu6dzckr56v63v4tguysnpz7fm` represents tokens which *began* unbonding in epoch 12 and will finish unbonding in epoch 15 (in this hypothetical, the `unbonding_epochs` chain parameter is set to 3).

This solution also changes the meaning of the `Undelegate` action, and adds a new `UndelegateClaim` action. Their meanings are as follows:

`Undelegate(R, V, S, E)`: for a given exchange rate `R` = staking or unbonding token / delegation token, value of that same delegation token `V`, start epoch `S`, and end epoch `E`, contributes to the value balance `- V` delegation tokens for that validator, and `+ V * R` unbonding tokens for that validator, with start epoch `S` and end epoch `E`. The rate and start/end epochs are in the clear; the amount undelegated is to be flow encrypted and paired with a balance commitment. Stateful checks must verify that the rate `R` is correct for the current epoch, the current epoch is equal to `S`, and the epoch `E` is equal to `S` + `unbonding_epochs`. We bind the end epoch at undelegation time, so that governance changes to unbonding duration do not affect unbondings in progress. This action has the effect of performing an exchange at time-of-undelegation from delegation tokens to unbonding tokens, using the rate at that time. Then, if no slashing occurs before unbonding completes, unbonding tokens (for all validators and all epoch starts/ends) have a 1:1 exchange rate with penumbra.

`UndelegateClaim(I, P, V, S, E)`: for a given *penalty* `P` for validator `I` representing the product of all slashing penalties applied during the half-open interval `[S, E)`, value `V` of an unbonding token parameterized by, start epoch `S` and end epoch `E`, contributes to the value balance `- V` unbonding tokens, and `+ (1 - P) * V` staking tokens. Stateless checks must verify that the start and end epochs `S` and `E` match the denom of the value `V`. Stateful checks must verify that the penalty `P` corresponds to the product of all slashing penalties for the validator in the interval `[S, E)`, and that the current epoch is greater than or equal to `E`. Note that the difference between `S` and `E` should *not* be re-checked in the claim verification, as it was checked when the unbonding token was minted during undelegation, and the unbonding epochs in the chain params could have changed since. This has the effect of completing a 1:1 exchange unbonding : staking tokens, completing the unbonding, applying a penalty if slashing occurred in the unbonding period. The penalty `P` and start/end epochs `S` and `E` are in the clear, but the value `V` has only its denomination revealed: the action itself contains a balance commitment to `V`, and a proof that opens the commitment and proves its denomination is equal to the unbonding token for validator `I` with start `S` and end `E` (but does not reveal the amount).

In order to implement the requisite checks, it's needed to track every time a validator is slashed in the state. We will need to add an additional key, something like `stake/slashed_in_epoch/<VALIDATOR_ID>/<EPOCH>`. It is ordered this way so we can do a range query to fetch all the slashings for a given validator, which we need to do to check `UndelegateClaim`.

Unlike swap claims, undelegate claims don't need pre-authorization machinery built in, for several reasons:

1. This makes them simpler to implement.
2. Unbonding takes a while, so it's okay for you to have to come back later and authorize another transaction (whereas doing this for every swap would be annoying).
3. The existence of "non-soulbound" unbonding tokens means there can be a market in unbonding tokens, so if you want to get out of unbonding early, you could swap, likely at a penalty rate of some kind.

Keeping track of unbonding tokens requires no special client machinery as they are notes like any other. The denomination is explicitly intended to be human-readable, but additional UI work could make it even more intelligible, performing aggregation or such.

**Comment by hdevalence** [comment]
> In order to implement the requisite checks, it's needed to track every time a validator is slashed in the state. We will need to add an additional key, something like `stake/slashed_in_epoch/<VALIDATOR_ID>/<EPOCH>`. It is ordered this way so we can do a range query to fetch all the slashings for a given validator, which we need to do to check `UndelegateClaim`.

Since our range queries work by lex order on byte strings, and we require those byte strings to be UTF-8, it seems like in order for this to work, we'd need to ensure that the `<EPOCH>` part of the encoding had leading zeros (effectively using "fixed-width decimal big-endian"), so that the lex order was the same as the numeric order.  Otherwise, I think we'd run into problems like having the range `/1../5` including `/12`, `/13`, and so on. Padding to 10 decimal digits is enough to cover 32-bit ranges, but it's annoying to have to define a width upfront.

**Comment by hdevalence** [comment]
> Do we want to make the tokenized logic/existing swap claim mechanism generic to some extent to support this and future programmability?

In discussions with @plaidfinch, we decided not to do this, because of the reasons now recorded in the (edited) proposal:

> Unlike swap claims, undelegate claims don't need pre-authorization machinery built in, for several reasons:
>
> 1. This makes them simpler to implement.
> 2. Unbonding takes a while, so it's okay for you to have to come back later and authorize another transaction (whereas doing this for every swap would be annoying).
> 3. The existence of "non-soulbound" unbonding tokens means there can be a market in unbonding tokens, so if you want to get out of unbonding early, you could swap, likely at a penalty rate of some kind.
>
> Keeping track of unbonding tokens requires no special client machinery as they are notes like any other. The denomination is explicitly intended to be human-readable, but additional UI work could make it even more intelligible, performing aggregation or such.

**Comment by hdevalence** [comment]
I'm not sure that parameterizing the unbonding tokens by start and end epochs correctly accounts for slashing, because the epochs are "coarse", and we may end up over- or under-counting slashings.  Suppose validator V is slashed, and consider two undelegations, U1 and U2, both submitted in the same epoch as the slashing, but with U1 submitted pre-slashing and U2 submitted post-slashing.  U1 and U2 will have the same denom and be fungible with each other, but U2 has the slashing priced in already, while U1 doesn't.

There are two ways out of this problem:

1. We could make U1 and U2 use the same exchange rate, which requires changing the way we apply slashing penalties;
2. We could make U1 and U2 not be fungible with each other, by making the start and end points parameterized by *blocks*, rather than epochs, to precisely track slashings.

On (1), we currently apply the slashing penalty to the validator's exchange rate immediately. Instead, we'd need to defer applying the penalty until the end of the epoch, and remember what penalty we should apply -- but that's data we have to remember anyways.

On (2), we'd have some issues, since we need to bind all the blocks in question at the time the transaction is created, but we don't at that time know what block it will be submitted in.  I expect we'd need to allow the user to declare the start and end block heights separately, and check that there were no slashings since the start height, and that end-start was long enough, or something. This seems worse and more complicated.

**Comment by hdevalence** [comment]
I started an initial stab at implementation of this in #1721

**Comment by redshiftzero** [comment]
Closing as done
