### ISSUE TITLE
Change `pviewd` to request assets individually rather than in a list

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1602]
**Is your feature request related to a problem? Please describe.**

Currently, `pviewd` uses the `AssetList` RPC https://buf.build/penumbra-zone/penumbra/docs/main:penumbra.client.v1alpha1#penumbra.client.v1alpha1.ObliviousQuery.AssetList to request a list of every known asset, every time it starts.  This was a temporary hack and isn't scalable.

**Describe the solution you'd like**

Remove use of the `AssetList` RPC from `pviewd` by replacing it with the `AssetInfo` RPC added in #1600. Then delete the `AssetList` RPC.

The work of this change is that it means that we won't just have one list of all of the assets any more. Instead, we'll need to figure out how to query the chain to fill in information about assets we're interested in, then store those locally in the `assets` table of the view service.  This is an information leak (it discloses time-of-first-receipt for each asset), which isn't great, but we'll live with it for now, and consider how best to patch it up later.

**Comment by aubrika** [comment]
Currently I think `pcli` requests the asset list in about seven different places, so this will be a refactor with several points of contact & potentially breaking changes of broader scope than I appreciated at first glance. I just want to make sure I'm understanding the intended scope of these changes correctly (i.e. that they are not actually constrained to the viewed, but will affect how pcli calls the view client - is that correct?) before I sink any more time into it - as it stands, I think this will be the work of a couple more days at least, since AssetList gets called many places & the surrounding logic is sometimes complex.

**Comment by hdevalence** [comment]
> understanding the intended scope of these changes correctly (i.e. that they are not actually constrained to the viewed, but will affect how pcli calls the view client - is that correct?)

The intention was just to change the RPC for the full node, and eliminate that specific API.  Since the view service maintains a table of assets that are relevant to it, we can leave the existing view protocol RPC https://buf.build/penumbra-zone/penumbra/docs/main:penumbra.view.v1alpha1#penumbra.view.v1alpha1.ViewProtocolService.Assets and its callers unchanged.

The only thing we need to figure out is how the view service should handle unknown assets while scanning.

**Comment by aubrika** [comment]
Cool, that's helpful scoping, thank you - I'll look at scanning following work on #1622
