### ISSUE TITLE
Encrypt `SwapPlaintext`s with the OVK

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1747]
Followup: should we be encrypting `SwapPlaintext`s with the IVK or OVK?

I'm not sure the distinction is particularly important, but we might be able to save a little bit of space + compute on the client side by using the (symmetric) OVK rather than the (asymmetric) IVK.

_Originally posted by @hdevalence in https://github.com/penumbra-zone/penumbra/pull/1736#discussion_r1045172946_

**Comment by hdevalence** [comment]
In discussion about #1688, we noted that we'd need to have an rseed-style construction for swap encryption (using `swap_blinding`) to prevent a similar class of attacks as the `rseed` construction does, but, that class of attacks is only possible because we use the IVK for encrypting the `SwapPlaintext`, allowing third parties to create swap ciphertexts. Instead, we could not do that, and use the OVK for swap encryption, which prevents the attack in the first place.

So using the OVK seems preferable to using the IVK.

**Comment by redshiftzero** [comment]
Proposed approach here is:
* Encrypt and decrypt swaps using the OVK
* The first 16 bytes of the swap commitment will be used for the nonce since swap commitments will be unique
* Remove ephemeral public key from the `SwapPayload` since it is no longer needed if we are encrypting/decrypting directly to the OVK
