### ISSUE TITLE
Build Planner service & API to fulfill requests for TransactionPlans

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#1782]
As described in #1775 , we need a way for wallets to build and prove TransactionPlans, which we can do with a new Planner service to handle requests and return the plan to be proven:

> We need a way for the wallet logic to ask for a TransactionPlan to be built and proved. It's already talking to the view service to get the data, and the view service already has access to viewing keys, so this could be a useful extension to the view service.
> Web trust model aside, this might also be useful for cross-language tooling/wallets, which can work with the generated proto types for TransactionPlan in their language, without having to pull in Rust code to do proving. For instance, this could be useful for integrating fee support into the Go IBC relayer.

- [ ] Add an RPC equivalent to the Rust `Planner` API
    - Proposed design:
        ```proto
        service PlannerService {
            rpc Planner(PlannerRequest) returns (PlannerResponse);
        }
        
        message PlannerRequest {
            message Output {
                core.crypto.v1alpha1.Value value = 1;
                core.crypto.v1alpha1.Address destination = 2;
            }
            message Delegate {
                core.crypto.v1alpha1.Amount unbonded_amount = 1;
                core.crypto.v1alpha1.IdentityKey validator_id = 2;
            }
            /* ... */
            repeated Output outputs = 20;
            repeated Delegate delegates = 30;
            /* ... */
            // Identifies the FVK for the notes to query.
            optional core.crypto.v1alpha1.AccountID account_id = 14;
            // Authorizes the request.
            optional ViewAuthToken token = 15;
        }
        
        message PlannerResponse {
            core.transaction.v1alpha1.TransactionPlan plan = 1;
        }
        ```
Note: we may be better served by a single repeated field of enums corresponding to each Planner method, to exactly match the Planner API & avoid any ordering concerns. This is also more extensible because you can just add another variant to the enum. Futureproofing: if a relayer is using this, then there is also no special support needed for intra-transaction ordering of actions, because an exact mapping of the Planner API will ensure calling the methods in the correct order.

We don't need domain types here, we can just work with the request structure, so this should be pretty simple to implement.
    - [ ] Fill out protos for `PlannerService`
    - [ ] Implement `PlannerService` wrapping the Rust `Planner` API

**Comment by aubrika** [comment]
@hdevalence is there any particular reason not to simply use the proto messages for Output, Delegate, etc. defined elsewhere, instead of recreating those as message subtypes? 

If we reference the existing protos we could get a more succinct implementation:

```
message PlannerRequest {
  
    // The expiry height for the requested TransactionPlan
    uint64 expiry_height = 1;
    // The fee for the requested TransactionPlan, if any.
    crypto.v1alpha1.Fee fee = 2;
    // The memo for the requested TransactionPlan
    string memo = 3;
    // Identifies the FVK for the notes to query.
    optional core.crypto.v1alpha1.AccountID account_id = 14;
    // Authorizes the request.
    optional ViewAuthToken token = 15;

  // Request contents
  repeated core.transaction.v1alpha1.Output outputs = 20;
  repeated core.transaction.v1alpha1.Spend spends = 30;
  repeated core.dex.v1alpha1.SwapClaim swap_claims = 40;
  repeated core.dex.v1alpha1.Swap swaps = 50;
  repeated core.stake.v1alpha1.Delegate delegations = 60;
  repeated core.stake.v1alpha1.Undelegate undelegations = 70;
  repeated core.stake.v1alpha1.UndelegateClaim undelegation_claims = 80;
  repeated core.stake.v1alpha1.ValidatorDefinition validator_definitions = 90;
  repeated core.transaction.v1alpha1.ProposalSubmit proposal_submissions = 100;
  repeated core.transaction.v1alpha1.ProposalWithdraw proposal_withdrawals = 110;
  repeated core.transaction.v1alpha1.ValidatorVote validator_votes = 120;
}
```

**Comment by hdevalence** [comment]
Yes, the reason is that the requester doesn't have the data in those messages, and that's why they're making the request — those are response data, not request data.

For instance, the PlannerRequest.Output message should just have a Value (the amount to send) and an Address (to send it to), and no other data, unlike the OutputPlan, which has other cryptographic data like blinding factors.

**Comment by aubrika** [comment]
ok cool - in that case, do we want the PlannerRequest to only include proto primitive types in its sub-message definitions, also? In trying to find out which data needed to be present in which newly-defined message type, I found myself largely recreating the existing protos in terms of what fields & types were present.

**Comment by hdevalence** [comment]
We can use our existing types, like `Value` or `Address`; the messages should be similar to the arguments to the corresponding methods on the `Planner`, since that's what the RPC is supposed to be wrapping.

**Comment by hdevalence** [comment]
Rather than working breadth-first, and trying to cover every possible kind of transaction, I think it'd make sense to work depth-first, and provide simplified access to common types.  Looking at the `Planner` API:

- Validator functionality (validator definitions, voting, etc) can be skipped, validators can use a command-line tool;
- Proposal functionality can be skipped for now, because it's in the process of being rewritten;
- Spends can be skipped, since the point of the API is that the required spends should be filled in automatically, and the API consumer shouldn't need to manage notes.

This leaves:

- `Output` -- let's start with this, since it's enough to transfer funds around as a test case; it needs a `Value` and an `Address`;
- `Delegate` -- this should just specify an `Amount` and an `IdentityKey`, and require the backend implementation to query the necessary `RateData`;
- `Undelegate` -- this should just specify a `Value`; the validator identity is implied by the delegation token;
- `UndelegateClaim` -- we could skip this, on the assumption that the viewserver/extension would automatically finish undelegations;
- `Swap` -- this should just specify a `Value` (amount and type) to swap from, an `AssetId` to swap into, and a `Fee` to prepay for the claim; the backend planner already knows the claim address;
- `SwapClaim` -- we could skip this, on the assumption that the viewserver/extension would automatically finish swaps.

Of `Planner.Output`, `Planner.Delegate`, `Planner.Undelegate`, `Planner.Swap`, all of these will have reduced/simpler data, so they make sense as sub-messages.

Starting with `Planner.Output` first means we can get it working end-to-end, and fill in the other functionality afterwards.
