### ISSUE TITLE
Ensure that we can recover the original `Transaction` from a `TransactionView` and have the hash match exactly

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#1788]
Part of #1775

**Comment by hdevalence** [comment]
#2176 would be a useful prerequisite for this.  Once we have that in place, the implementation strategy could be something like:

- Add a `TransactionView::transaction(&self) -> Transaction` method with a `todo!()` body
- Add a proptest that we can start with a transaction, view it, and then recover the original transaction
- Fix the `TransactionView` data modeling until the test stops failing

The problem with that strategy, though, is that what we really want to exercise is that _all possible views_ of a `Transaction` allow recovery of the original `Transaction`, and just generating `Transaction`s isn't enough for that.  We'd also need to have a strategy for generating `TransactionView`s.  But that strategy depends on the definition of the `TransactionView`, which is what we're trying to change/align in the first place!

So, instead, I think we should do this strategy:

- [ ] Add a `TransactionView::transaction(&self) -> Transaction` method;
- [ ] Fill in the implementation, relying on Rust's exhaustive matching checks to detect any places where the `TransactionView` data modeling might be missing a field from the original `Transaction`.

Zooming out, I think this is probably OK, because I think that we're much less likely to have bugs of the form "we wrote a recovery method but we copied the wrong data" than "we can't write the recovery method at all, because the data is missing", and proptesting helps with the former rather than the latter.
