### ISSUE TITLE
Make `tonic` an optional dependency for `penumbra-chain`

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1857]
**Is your feature request related to a problem? Please describe.**

Currently, `penumbra-chain` can't be used in wasm, because it depends on `tonic`.

**Describe the solution you'd like**

Determine why `penumbra-chain` depends on `tonic`, and make it optional.

**Comment by conorsch** [comment]
This might unblock ungoing work by Zpoken, so I'll take a crack at it for 43.

**Comment by conorsch** [comment]
```
❯ rg tonic chain/
chain/Cargo.toml
32:tonic = "0.8.1"

chain/src/view.rs
80:    async fn check_chain_id(&self, provided: &str) -> Result<(), tonic::Status> {
84:            .map_err(|e| tonic::Status::unavailable(format!("error getting chain id: {}", e)))?;
88:            Err(tonic::Status::failed_precondition(format!(
```

Looks like it's only used for a few error return types. We can handle that outside the crate in the callers in order to drop the `tonic` dependency for the `chain` crate. My understanding is that The Right Way to do this would be to use intermediate error types and custom `From` implementations, but in the interest of unblocking, I'll opt to commit the sin of `.map_err()` and explain in comments.
