### ISSUE TITLE
Change domain types for keys and addresses to store bytes and defer expensive crypto operations until use.

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#1957]
**Is your feature request related to a problem? Please describe.**

Our domain types for cryptographic keys perform some crypto operations during parsing.  For instance, verification keys decompress the group element, and our `Address` type computes the diversified basepoint.

This was originally done as part of a "parse, don't validate" approach, but it imposes real costs, because it means that every time we pass back and forth between bytes and domain types, we pay for the precomputation, even if we'll never use it. For instance, the only time we actually use an `IdentityKey` as an identity key is when we verify updated validator configuration data, and at all other times it's just used as an identifier. But we pay the cost at all times.

In other cases, this is even more wasteful: our binding and spend authorization signatures only ever use the same verification key once, so there's no possible benefit to precomputation, rather than waiting to decompress the verification key while processing the signature.

However, it is good to prevent fallibility from propagating through the codebase, so if not doing some check in decompression would result in operations that are currently infallible becoming fallible, we shouldn't defer it. (As a counterexample, deferring decompression of a verification key doesn't introduce any extra fallibility, because signature verification can already return an error).

**Comment by hdevalence** [comment]
One sub-case of this that could be worth doing sooner is the `IdentityKey`, which is currently a significant fraction of the total sync time.

**Comment by hdevalence** [comment]
We should do at least the `IdentityKey` and ZK proof changes prior to mainnet.

**Comment by redshiftzero** [comment]
The zk proof part of this was done in https://github.com/penumbra-zone/penumbra/pull/2610

**Comment by cratelyn** [comment]
x-ref #4152.

**Comment by cratelyn** [comment]
`Address` is mentioned in the description, i would be interested in handling that as well this week.

**Comment by cratelyn** [comment]
> `Address` is mentioned in the description, i would be interested in handling that as well this week.

following up on this:

https://github.com/penumbra-zone/penumbra/blob/4fce95321275e52d61ddd0fa966cc3716b483bbb/crates/core/keys/src/address.rs#L26-L29

the `g_d` field today helps deduplicate calls to `Diversifier::diversified_generator()`, which i understand to be the expensive computation in converting a `pb::Address` to the internal `Address` domain type, which we'd like to defer. that means that removing `g_d` and exposing calls to `address.d.diversified_generator()` would represent a regression, as [`Address::diversified_generator()`](https://github.com/penumbra-zone/penumbra/blob/4fce95321275e52d61ddd0fa966cc3716b483bbb/crates/core/keys/src/address.rs#L86) is used in many places.

in #4151 i'd explored using `OnceLock::get_or_init()` to only perform an expensive operation once. in the case of `IdentityKey` in particular that was not the right choice, because we only need to decompress the bytes once. is `OnceLock<T>` a better choice for address' diversified base, or is there another way of modeling this that you'd prefer, @hdevalence?

as for `transmission_key_s`, deferring that seems like it would be a more disruptive change, and would violate the "_so if not doing some check in decompression would result in operations that are currently infallible becoming fallible, we shouldn't defer it_" rule in the original description. see... https://github.com/penumbra-zone/penumbra/blob/4fce95321275e52d61ddd0fa966cc3716b483bbb/crates/core/component/dex/src/swap/plaintext.rs#L98-L120 ...which would become fallible if decompressing the s value was deferred.
