### ISSUE TITLE
Add `pcli address view`

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#2007]
Following #1972, it would be nice to have a way to view addresses via pcli and be able to determine whether those addresses are part of / visible to a given account.

**Comment by hdevalence** [comment]
On the `pcli address view` vs `pcli view address` point, we want it to be the latter so that we don't add a bunch of random subcommands, and instead group them by mode: query, view, transact, etc.  Splitting into "query" and "view" reinforces the separation between public chain state and private per-user data.
