### ISSUE TITLE
Implement checked fixed-point arithmetic 

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#2014]
Building off the work in #2008 - we want to be able to perform fixed-point arithmetic that is checked by default. One approach to do this, is to implement the `std::ops` binary operators such that their associated type [`Output`](https://doc.rust-lang.org/std/ops/trait.Add.html#associatedtype.Output) wraps the fixed-point struct into an `Option` (`None` when overflow).

The idea is to end-up with an api that lets you combine a sequence of operations which result in an `Option` that the user has either `unwrap`, or `expect` and motivate why its specific application would work.  One of the advantage of this approach is that the failure mode for an out-of-bounds error becomes easier to model (fail-stop). 

- [x] implement basic arithmetic operations (`Add`, `Sub`, `Mul`, `Div`)
- [ ] an efficient way to divide 
- [x] faillible conversion to `Amount` (fails for non-integral fixed-points 
- [x] bytes encoding/decoding
- [ ] property testing

**Comment by hdevalence** [comment]
The idea we'd discussed was to implement all but the last of those impls, and use the need to extract an inner value as a way to force the caller to either

1. `.unwrap()`, declaring they don't care about overflow checking, but still panicking rather than allowing silently invalid data;
2. `.expect()`, with a justification for why the operation can't overflow;
3. error out with conversion to an error.

We could instead make our own not-an-`Option` type, but it seems like we'd either have to have worse ergonomics, or spend a lot of effort duplicating option combinators.

To start, it seems simpler to use a bare `Option`; if not being able to operate on two `Option<UInt128x128>` is unbearable, we could switch to our own type.
