### ISSUE TITLE
Design and implement transaction intents

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#2076]
Prerequisites:

- [x] #2082
- [x] #2081

Postrequisites:

- [x] #2078
- [x] #2079

**Comment by hdevalence** [comment]
Before we go to all of the component pieces, could we write up an overview of what is being built and why?

**Comment by hdevalence** [comment]
Before we go to all of the component pieces, could we write up an overview of what is being built and why?

**Comment by hdevalence** [comment]
I don't think we should do this at the present. We currently have, effectively, three different variants of every `Transaction` structure: the "plan", the "tx", and the "view", and we are already struggling from a process perspective to keep up necessary or backlogged changes.

For instance, the `TransactionView` structures need to be rewritten so that it's possible to actually recover the transactions they view (https://github.com/penumbra-zone/penumbra/issues/1788), but that issue has fallen through the cracks and we haven't had time to pick it up.

Similarly, we need to have an `AddressView` for a much more pressing reason -- as part of the baseline requirements for keeping long-term keys out of web frontends -- but our planning for https://github.com/penumbra-zone/penumbra/issues/2037 also fell through the cracks.

I don't think we can presently afford -- in terms of our time and attention -- to add a fourth variant of our transaction data structures in pursuit of perfect transaction comprehension. We need to get the basics right first. We can always revisit this problem space post-mainnet, since it's not consensus-critical, and clients can be freely updated whenever.
