### ISSUE TITLE
Prevent un-intentional external restarts when chain tries to halt

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#2085]
Software like systemd and kubernetes restarts processes when they stop. This will likely mean that if the majority use this to manage their deployments, an emergency chain halt... won't halt the chain. We need to prevent this.

Suggested solution: if `pd` starts up and the last chain halt occurred in the most recent block, check for an environment variable `PD_RESTART_CHAIN_FROM=N` where `N` is the block height of the last halt. This variable can't be set once-and-for-all, and must be intentionally set by the person restarting the software, which means auto-restarts will fail until manual intervention. Thanks @conorsch for bringing up this issue.

**Comment by hdevalence** [comment]
As a simpler and more robust alternative, the chain halt hook can write a "halted" key into the nonconsensus store, and pd can check that that key is not present on startup. Then we don't need any environment variable handling, or block height checks, etc.

Resuming after a halt isn't a concern, because there's no situation in which an emergency chain halt should happen that doesn't also result in restarting with a hotfixed version of pd.
