### ISSUE TITLE
Prevent tombstoned validators or their delegators from voting on governance proposals

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#2111]
Tombstoned validators no longer have a stake in the protocol. I posit that their delegators, who are forcibly unbonded, also should be barred from voting, though this seems less important.

**Comment by hdevalence** [comment]
I don't think we should do this -- it seems like this complication to the state machine is only necessary because of the decision to ban them from voting.

Elsewhere, the system is designed with the idea that voting power doesn't change after voting begins.  Why should tombstoning be different? If we ban tombstoned validators from voting, we now have to introduce an additional modality into the governance state machine: "under MOST circumstances, voting power does not change after voting begins, except in this rare special case that's unlikely to be triggered in practice".

This additional modality feels like a large increase in bug surface area for very little concrete benefit -- at the point that tombstoned validators are swinging governance votes, the chain probably has much deeper problems.
