### ISSUE TITLE
Create testnet allocation with multiple paper assets

### ISSUE THREAD

**Issue by zbuc** [penumbra-zone/penumbra#2229]
To facilitate development of the market maker bot and testing of dex functionality, the testnets should come pre-loaded with some allocations of simulated "paper assets" representing common currencies, e.g. ETH, BTC, USDC, etc.

_Originally posted by @zbuc in https://github.com/penumbra-zone/penumbra/issues/2204#issuecomment-1483169813_

**Comment by hdevalence** [comment]
Let's do this after #2251 ?

**Comment by conorsch** [comment]
Do we still want this for 52? We haven't bumped the chain id for 52 yet, and I assume we should do this prior to regenerating if we want it in.

**Comment by zbuc** [comment]
I think we need a clearer guideline for what this would look like. Does this just mean:

1) define some additional assets in the initial registry (ETH, BTC, etc)
2) add distributions for those to galileo
3) add extra-bonus distributions for those to testnet market maker address(es)

@hdevalence @erwanor thoughts? ^^

**Comment by erwanor** [comment]
I think starting with `pETH`, `pBTC` is good, in addition to the galileo allocation, we should make sure that the bot in #2204 has a significant amount of the total float so that it can simulate doing arbitrage.

**Comment by erwanor** [comment]
I added a comment about why this is needed in the description of #2204

**Comment by hdevalence** [comment]
I don't think we need to have Galileo allocations, since people can get those other paper assets by trading on the DEX.

In terms of assets, maybe we should have:

- ETH
- BTC
- USD
- ATOM
- OSMO

I'm not sure what the best naming scheme for these denoms is. It seems important to not have any ambiguity that they're made-up test assets, not real ones (e.g., what happens if, in a later testnet, someone makes an IBC connection to the hub, transfers some fake test atoms out, and then the orphaned tokens live there forever? they'd be bound to the connection/channel, but still potentially confusing).

Maybe we should use `test_` instead of `p`, like `test_eth`, `test_usd`, `test_atom`?

**Comment by hdevalence** [comment]
We should also generate a new mnemonic (stick it in 1Password) and give it a whale-sized allocation of the test tokens, so that next week (or at any point in the meantime) we can use it for #2204

**Comment by zbuc** [comment]
Closed by #2491
