### ISSUE TITLE
Integrate Libra's Jellyfish Merkle Tree

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#249]
Penumbra's user data is shielded and recorded using a SNARK-friendly incremental Merkle tree. However, we also need an ordinary Merkle tree to record public chain data, like info about the validator set, IBC data, etc.

Libra's [Jellyfish Merkle Tree](https://diem.github.io/diem/diem_jellyfish_merkle/index.html) seems like a good choice. We should make a plan for how to integrate it into Penumbra, including (1) how we want to include the tree root in the AppHash and (2) how we want to write the backing data to Postgres.

**Comment by aubrika** [comment]
Following our discussion today, it has become apparent that since the JMT requires data represented in kv-store format, there will be significant design and development overhead in translated structured relations/datasets into the required kv format. A Merkle tree is "basically a kv store with extra stuff", and everything references data within the Merkle tree, so everything needs to be compatible with querying, utilizing, and storing data in this format. Additionally, the backing store of the JMT is precisely equivalent to a kv-store (just get/put/max). We can implement a kv-store trivially in Postgres, but leveraging useful relational DB features in Postgres requires ditching those structural/schema features to persist state/delta in the JMT. Because we will necessarily flatten the structure to track state in the JMT, this might be a strong argument for utilizing a kv-store directly as our primary backing data store, as long as it will support efficient querying that we know we will need to do. Utilizing a composite key for a kv-store could provide a directory-like query structure (e.g. validator/version/website or similar) that could allow us to request highly specific data, while also allowing us to track changes to entities without needing to append redundant data to the tree. This is no blocker for next steps around importing the JMT to the codebase but should be discussed before wiring up with the existing Postgres DB.

**Comment by aubrika** [comment]
Moving to a kv-store would need to support tracking versions for unique entities in such a way that we could query for latest/highest versions, as well as ranges spanning multiple versions over data where updates have not occurred since the latest version update.

**Comment by aubrika** [comment]
Prospective next steps following discussion:

1. Import JMT crate to Penumbra, implement `TreeReader` & `TreeWriter` for minimal backing store consisting of (version, nibble_count, nibble_path) key and byte value as expected by JMT.

2. Add second two-column table to track latest version of inserted data by JMT hash, as latest version is not clearly tracked or available in exposed interface.

3. Write type-safe Rust implementation for key definitions as used for 2.

**Comment by aubrika** [comment]
Forked JMT code is integrated and reading/writing NCT root hashes appropriately.
