### ISSUE TITLE
Redesign routing execution 

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#2507]
#### How does routing execution currently work?

We build off the assumption that there is a way to route a positive amount of capacity over the provided route that has an end-to-end effective that's better or similar to the specified `spill_price`. 

First, we pick the first position on the first hop and simulate execution over the entire route. If routing flow is bottlenecked at any position, we identify that position as a limiting constraint, track it, and continue routing capacity through the remaining hops. At the end of the simulation, we know whether we can execute the entirety of the first order, or if we must deal with a more constraining position first ("lift the constraint").

If no limiting hops were found, that's great we execute that amount and try again until spill price is hit. If some constraints were found, we pick the most limiting one, compute its saturating input i.e. $\Delta^*_1$ such that when we execute over the route again we exhaust that constraint. The reason we are able to do this without fearing getting bottlenecked by another hop along the route is because we explicitly picked the most limiting constraint i.e. no other position along the route will bottleneck execution. Once the constraint is lifted, we can proceed again from the start, trying to route as much flow as possible until the position is filled or the `spill_price` is hit. 

#### Why this does not work

However, the current design of routing execution does not take into account the possibility that lifting the most limiting constraint may result in an output that exceeds the capacity of the next constraint on the route. This is a capital error (manifested in #2484) and a serious flaw in the current design of routing execution.

##### Interim proposed solution:

In addition to selecting the saturating input ($\Delta^*_1$) that lifts the most limiting constraint, we should simulate execution and backtrack until we find some amount of routable flow across the route.  This solution adds overhead to an already quadratic algorithm, but will let us work on the DEX concurrently as we work to improve it. 

### Dust swaps and dust positions

Dust swaps and dust positions are a class of undesirable behavior that happen when provisioning an action (position, or swap) with infinitesimal amounts of reserves. While these limitations of the DEX engine are not directly related to routing execution, they are still important to consider and should be given priority in any future improvements to the system. The DEX engine works with limited precision: a `U128x128` fixed-point type which handles pricing and quantity transformations, and an integral `Amount` type which is 128 bits wide and stores denoms scaled numbers such as the reserves $R_1, R_2$, the objective valuations of each assets $p, q$, and the input/output amounts $\langle (\Delta_1, \Delta_2), (\Lambda_1, \Lambda_2) \rangle$

When we execute against a position, we feed a tuple $(\Delta_1, \Delta_2)$ and obtain an output $(\Lambda_1, \Lambda_2)$ from execution. Internally, execution is handled by multiplying the input $\Delta_1$ by the exchange rate $\frac p {q \gamma}$ between assets 1 and 2. However, when $\Delta_1 \lt \epsilon$ is very small, computing the output $\Lambda_2 = \lfloor {\Delta_1 \cdot \frac p q \cdot \gamma} \rfloor = 0$. (as manifested in #2499) as well as in the early design discussions about implementing routing execution. This is a dust swap i.e. a swap that submits inputs and receives no outputs, and the reason why the current dex design does not support NFT transactions of `cube`. Our thought process was that this was an acceptable tradeoff for our first iteration of the DEX engine, and that swap inputs were to be denom scaled anyway (i.e. swapping 1gm -> $\Delta_{gm} = 1,000,000$). However, in the process of executing a route, it is possible that a swap will be partially filled up to some dust amount, triggering this scenario, or that attempting to lift a very limiting constraint becomes tantamount to routing a dust flow that recreates this scenario, as it is the case in #2499. 

##### Interim proposed solution:

I propose that burning dust might actually be the correct behavior for the current system we have, which is not to say that a better system is not possible or what we should be aiming for.

**Comment by hdevalence** [comment]
The core problem here is one that we've been concerned about from the start: how to ensure that when we fill against a position, we completely exhaust its reserves, so that we can eliminate it from consideration in further routing.  In the current fill code, we don't do this properly, which leads to the problem we're seeing where filling loops indefinitely.  Even if we did a fix to just that part (e.g., by skipping positions we've already executed against), it wouldn't solve the problem, because we could run into it again at the next higher level: in the next iteration of path search, we'd still be searching through positions with dust reserves.

To ensure that the fill phase always makes progress, we need to ensure it upholds the following invariant: in each iteration of the fill phase, **EITHER**:

* we completely fill the input trade, exhausting the input amount to 0;
* we completely fill at least one minimally-priced position, setting its reserves to 0.

We need to change the structure of the fill step so that we can see that this invariant is always upheld: we should know whether we're in the exhaust-input case or the exhaust-reserves case, and in the latter case, to be able to identify which position we'll be exhausting. To do that, one helpful simplification would be to disallow cycles at the micro-scale, ensuring that all positions on the fill path are distinct, letting us compute exact input and output amounts along the path.
