### ISSUE TITLE
`SwapClaim` transactions are not viewable by the view server

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#2547]
**Describe the bug**

`SwapClaim` transactions are not viewable by the view server:
```
~/c/p/penumbra (bsod-rename-unfilled|✔) $ cargo run --release --bin pcli -- -n http://localhost:8080 tx swap 1000test_usd --into penumbra
    Finished release [optimized] target(s) in 0.35s
     Running `target/release/pcli -n 'http://localhost:8080' tx swap 1000test_usd --into penumbra`
Scanning blocks from last sync height 48 to latest height 222
[0s] ██████████████████████████████████████████████████     174/174     4628/s ETA: 0s
building transaction...
finished proving in 0.980 seconds [2 actions, 1 proofs, 1169 bytes]
broadcasting transaction and awaiting confirmation...
transaction confirmed and detected: fcd213335856605d149ba685953bcff86dbac7c2d616a7f988b0b1d6c489d6e4
Swap submitted and batch confirmed!
You will receive outputs of 0test_usd and 100penumbra. Claiming now...
building transaction...
finished proving in 0.001 seconds [1 actions, 0 proofs, 3179 bytes]
broadcasting transaction and awaiting confirmation...
transaction confirmed and detected: e80cfeef60ba0d1e6be7aefcb3b121eb9435508f1c3b8575769620d0e2c5f419
~/c/p/penumbra (bsod-rename-unfilled|✔) $ cargo run --release --bin pcli -- -n http://localhost:8080 view tx e80cfeef60ba0d1e6be7aefcb3b121eb9435508f1c3b8575769620d0e2c5f419
    Finished release [optimized] target(s) in 0.34s
     Running `target/release/pcli -n 'http://localhost:8080' view tx e80cfeef60ba0d1e6be7aefcb3b121eb9435508f1c3b8575769620d0e2c5f419`
Scanning blocks from last sync height 223 to latest height 227
[0s] ██████████████████████████████████████████████████       4/4       236/s ETA: 0s
Transaction not found in view service, fetching from fullnode...
 Action Type  Description
 Swap Claim   Opaque swap claim for trading pair: passet14h46dmcyy6fl5vyz7xx933n8l7jy202ahrxg92kad6yfladsvcyqczcwda <=> passet1984fctenw8m2fpl8a9wzguzp7j34d7vravryuhft808nyt9fdggqxmanqm with fee 0penumbra

 Transaction Fee                0penumbra
 Transaction Expiration Height  0
 ```

**Expected behavior**

There are at least two issues here:

1. The trading pair is unknown, meaning that the relevant denoms aren't being included in the TxP.  (Even if the swap claim were someone else's transaction, I should still be able to see the denoms of what pair it was claiming, that's public)
2. The transaction isn't viewable because it's not found in the view service. This could be because we're not flagging the transaction as one we should download?

**Comment by aubrika** [comment]
In the process of researching this bug, I found that there is something wrong with our transaction hash parsing in the view client - though pcli is able to use the same storage retrieval method without issue, hitting the rpc endpoint with the same tx hash in buf studio returns no transaction info, even though direct inspection of the database confirms the presence of a transaction with the given hash. Debugging continues.

**Comment by hdevalence** [comment]
Spooky, can we open a new issue with a repro to track that?

**Comment by aubrika** [comment]
Testing on this revealed that since there is currently no `SwapClaimPayload` implementation or logic, your intuition seems to have been correct: those automatically-generated SwapClaim transactions aren't being identified, trial-decrypted, and stored during client sync - testing is ongoing to verify, but hopefully the existing logic can just be extended to include the SwapClaim case.

**Comment by aubrika** [comment]
Latest discovery from prior test branch is that the swap output commitments are not being found in the SCT - this could indicate that they're being cleaned up or forgotten when they shouldn't be, or not being stored in the first place (or something else) but this is still unknown.

**Comment by conorsch** [comment]
@redshiftzero has made significant progress here. There's WIP in #3165. @redshiftzero will post a report here updating the current status on the WIP impl.

**Comment by conorsch** [comment]
Higher priority is the summonerd integration tests in https://github.com/penumbra-zone/penumbra/issues/3189. Those are must-have for Testnet 63 Rhea. Once those are in, we'll revisit this work, possibly via @redshiftzero or else @aubrika.

**Comment by redshiftzero** [comment]
I was able to reproduce this. #3165 should resolve the first issue if the denoms are known. My understanding of the second issue is that:
1. The `SwapClaim` transaction is not being downloaded
2. We get information about the `SwapClaim`s via the nullifiers field of the `CompactBlock`, which will have one entry per claimed swap.  There is no `NotePayload` implementation for `SwapClaim`s as correctly pointed out above. 

In the JMT we do have the transaction ID that spent the nullifier (via `state_key::spent_nullifier_lookup` in the shielded pool). We could either:
 * add a `NotePayload` type for `SwapClaim`s that sets `NoteSource::Transaction{id}`
 * or, otherwise annotate the nullifier with the transaction ID that spent that nullifier

Either solution will let us know to download the correct transaction.

**Comment by aubrika** [comment]
Regarding the latter issue, it turns out that the view storage `give_advice` function was explicitly not storing notes with an output value of 0 ... which is why, since the swaps were generating zero-value output notes, we were not later able to find those zero-valued outputs to display as part of a swap claim transaction, which was also breaking `list-tx-hashes`. 

Removing the lines that skip outputs of value 0, instead storing them for later reference, seems to fix the issue:

`aubrey@penpro penumbra % cargo run --release --bin pcli tx swap 1gm --into gn                                                
    Finished release [optimized] target(s) in 0.70s
     Running `target/release/pcli tx swap 1gm --into gn`
Scanning blocks from last sync height 145123 to latest height 145123
[0s] ██████████████████████████████████████████████████       0/0       0/s ETA: 0s
building transaction...
finished proving in 0.942 seconds [2 actions, 2 proofs, 1153 bytes]
broadcasting transaction and awaiting confirmation...
transaction confirmed and detected: b2356a93f0b5fb9ce68c812404fccb8cdd3c0b346f23567b96f83e8bf3c6f688 @ height 145124
Swap submitted and batch confirmed!
**You will receive outputs of 0gm and 1gn. Claiming now...**
building transaction...
finished proving in 0.659 seconds [1 actions, 1 proofs, 562 bytes]
broadcasting transaction and awaiting confirmation...
transaction confirmed and detected: 5671c32c58c1de539c450fb71ee32ad945900dcc7815ecb0cc6061097661719e
aubrey@penpro penumbra % cargo run --release --bin pcli v tx 5671c32c58c1de539c450fb71ee32ad945900dcc7815ecb0cc6061097661719e
    Finished release [optimized] target(s) in 0.60s
     Running `target/release/pcli v tx 5671c32c58c1de539c450fb71ee32ad945900dcc7815ecb0cc6061097661719e`
Scanning blocks from last sync height 145128 to latest height 145128
[0s] ██████████████████████████████████████████████████       0/0       0/s ETA: 0s
 Action Type  Description                    
 Swap Claim   Claimed 1gn with fee 0penumbra 
                                          
 Transaction Fee                0penumbra 
 Transaction Expiration Height  0         
aubrey@penpro penumbra % cargo run --release --bin pcli v list-tx-hashes                                                     
   Compiling penumbra-view v0.63.1 (/Users/aubrey/Repos/penumbra/crates/view)
   Compiling penumbra-wallet v0.63.1 (/Users/aubrey/Repos/penumbra/crates/wallet)
   Compiling pcli v0.63.1 (/Users/aubrey/Repos/penumbra/crates/bin/pcli)
    Finished release [optimized] target(s) in 44.44s
     Running `target/release/pcli v list-tx-hashes`
Scanning blocks from last sync height 145171 to latest height 145171
[0s] ██████████████████████████████████████████████████       0/0       0/s ETA: 0s
 Block Height  Transaction Hash                                                 
 15939         b03b319258e7495dac8c89fa24ec11a639df5a2fd70e24c96cdacbd4cfffc22d 
 17508         2e4f4e6beede5e5a6246254268f28412e085fc921fc956adb3910946a74c064c 
 94056         373faca1adbea709455bf47e5be2a47caa065cb922ad06da407a6ce7d9c4e761 
 94069         523aed7d9b0098a80c973b035a42e7aa6009384354f5bc40fb3f7154a2f32f92 
 127590        e7904fecccb393a9115e975fb8e7f103d59e6a5003d90b27a464c1567634ba39 
 127600        f97c3a352c8ca61f1dc486d448dab880468c7b28d19ec2816007897b08d7ff92 `
