### ISSUE TITLE
`ArbExecutions` and `SwapExecutions` RPCs don't work

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#2674]
**Describe the bug**

The `ArbExecutions` and `SwapExecutions` RPCs don't work.

**To Reproduce**
1. Go to https://grpcui.testnet.penumbra.zone
2. Make an `ArbExecution` request for height 30729
3. See that an arb occurred.
4. Make an `ArbExecutions` request without any bounds
5. See that no data is returned.
6. Make a `SwapExecution` request with the following data:
```json
{
  "height": "30819",
  "tradingPair": {
    "start": {
      "inner": "KeqcLzNx9qSH5+lcJHBB9KNW+YPrBk5dKzvPMiypahA="
    },
    "end": {
      "inner": "reum7wQmk/owgvGMWMZn/6RFPV24zIKq3W6In/WwZgg="
    }
  }
}
```
7. See that a swap occurred.
8. Make a `SwapExecutions` request with no bounds
9. See that no data is returned.

**Comment by zbuc** [comment]
This was fixed in https://github.com/penumbra-zone/penumbra/pull/2646/commits/9647a32cd5a750293328a4ce55d36291f61d3f7c but this issue was created prior to those changes being deployed. I just went to https://grpcui.testnet.penumbra.zone/ and verified that `SwapExecutions` and `ArbExecutions` both returned data.
