### ISSUE TITLE
Transaction Hash parsing error in transaction_info_by_hash

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#2844]
_Originally posted by @aubrika in https://github.com/penumbra-zone/penumbra/issues/2547#issuecomment-1639130720_

Repro steps:

Start pclientd: `cargo run --release --bin pclientd -- --home ./ start`

Using buf studio, no transaction info is returned.

<img width="1440" alt="Screen Shot 2023-07-18 at 09 36 46" src="https://user-images.githubusercontent.com/73075391/254333112-5b30fe4a-ed08-4525-aed2-582c9e236c6f.png">

A `pclientd` debugging branch with added console output shows the wrong hash on the storage level:

<img width="1440" alt="Screen Shot 2023-07-18 at 09 38 08" src="https://user-images.githubusercontent.com/73075391/254333451-ad3ad99b-835a-4983-903c-651e5d5fc248.png">

But, the transaction is viewable in `pcli v tx`:

<img width="1440" alt="Screen Shot 2023-07-18 at 09 40 16" src="https://user-images.githubusercontent.com/73075391/254333771-a1a55348-4417-4bfb-9adc-59d0c9fc295f.png">

Likewise, the transaction hash is available in DBBrowser in local storage:

<img width="1440" alt="Screen Shot 2023-07-18 at 09 41 19" src="https://user-images.githubusercontent.com/73075391/254334088-97b5fb54-a151-415d-af02-f637ac9ec1cb.png">

From this research, it appears we are doing the conversion wrong somewhere - pcli is calling the same storage function in a way that returns data, while the ViewClient protocol is not digesting the hash correctly from the web frontend. 

Still unknown where exactly the hash is being read or parsed incorrectly, debugging continues.

**Comment by hdevalence** [comment]
From looking at the first Buf studio screenshot, I suspect the problem is that the hash is being supplied as a hex string rather than a base64 string.  The ProtoJSON encoding always uses base64 to encode byte data, no exceptions, precisely to avoid this kind of problem. 

I'm surprised that supplying a hex string doesn't cause an error -- that seems like a bug, and we should fix it.  It looks like the supplied hex string _is_ a valid base64 string, but of the wrong length.  Looking at the second screenshot, the wrong hash being sent to the storage seems like the wrong length (though I didn't count carefully).

To test this on MacOS, you can convert a hex string from the clipboard to base64 using `pbpaste | xxd -r -p | base64`.

For instance
```
$ echo "708eced0719d84f02dbe5c61e150fe5968c1d87f21d9e8b089be1b9072c67304" | xxd -r -p | base64
cI7O0HGdhPAtvlxh4VD+WWjB2H8h2eiwib4bkHLGcwQ=
$ echo "708eced0719d84f02dbe5c61e150fe5968c1d87f21d9e8b089be1b9072c67304" | base64 -d | xxd -p
ef4f1e71e774ef5f5df387f4d9d6dee5ceb57b5e747dee7debc73577cedf
db577d7bc6f4f3d6ded5bf74ef673aef7d38
```

It seems to me like there are two problems here:

- [ ] Determine where the length check didn't happen
- [ ] Consider adding an `alt_hex` field to the proto message that would allow an RPC user to supply a hex string *instead* of the bytes (xref https://github.com/penumbra-zone/penumbra/pull/2848#discussion_r1267889132)

**Comment by aubrika** [comment]
It appears that rather than a missing length check, we were thwarted in part by the fact that `hex::encode` doubles the length of byte strings passed as arguments to it, while the default string formatting for debug or println output of those strings was quietly failing to mention that two strings displayed identically might also be of different lengths. Explicit logging of byte array lengths revealed the issue where it surfaced. Remaining work is to converge on a solution for the client code that supports both existing pcli string-parsing use cases and intended use cases by ensuring that the photos are properly documented and being parsed correctly.

**Comment by conorsch** [comment]
Fixes did not make Testnet 58, but we're actively working on them.

**Comment by aubrika** [comment]
The issue here seems to have been a documentation/API issue, where a mismatch in encodings in pcli (using hex) vs the serde json encodings (using base64) was not documented in the protos, as suggested in comments above - the base64 encoding has since been confirmed to work as designed with the client endpoint, and the proto documentation will be updated accordingly.
