### ISSUE TITLE
Determine changes to the `Component` trait needed for Astria to use it directly

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#3126]
As part of #3125, we want Astria to be able to use the `penumbra-ibc` crate as their IBC implementation. 

For Astria to use the `penumbra-ibc` `Component` implementation, it should be using the exact same `Component` trait as the other Astria components. In the design meeting last Thursday, it sounded like the Astria team had forked the `Component` trait to make some tweaks to it (largely about error modeling?).

As a first step, we should collect feedback from the Astria team about changes to the `Component` trait and then align both projects on a common interface.

cc @noot

**Comment by hdevalence** [comment]
@noot I would have assigned this issue to you but I think I can't do that since you're out of the penumbra-zone org; can you self-assign?

We can pick up making the required changes on our side once we align on what they are.

**Comment by noot** [comment]
@hdevalence unfortunately I can't self assign either :( 

here is the astria `Component` trait: https://github.com/astriaorg/astria/blob/main/crates/astria-sequencer/src/component.rs

I think the main difference is we removed `end_epoch` since we aren't using epochs at the moment. we also added `Result` returns to all the methods, although I don't think that's strictly necessary (as we can just panic inside the function, because either way the app is going to go down). the main motivation for adding the `Result`s is just so the error can be bubbled up before the app goes down, but I don't feel strongly about that.

**Comment by hdevalence** [comment]
@noot Can you clarify if we actually need to do this in order for y'all to use the `penumbra-ibc` component? If (like us) you're not actually writing code that's generic over components, and just using it as a way to have common behavior, this might not be on the critical path, correct?

**Comment by noot** [comment]
@hdevalence i don't think we need this - i've added the IBC code needed for ICS20 transfers and this hasn't come up, so should be fine as-is!

**Comment by avahowell** [comment]
Closing this then, since tentatively the current component trait design should work
