### ISSUE TITLE
Add a standalone node to testnet deployments

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#3336]
**Is your feature request related to a problem? Please describe.**

We need `pd` to work out of the box. But we don't test this anywhere, because we wrap it up in a bunch of infrastructure that hides broken behavior: #3281

**Describe the solution you'd like**

Add a node to the deployment that runs a full node the way we expect users to be able to: `pd start --grpc-auto-https mydomain.com` and `cometbft start`, no load-balancing, no reverse proxies, etc.

**Comment by conorsch** [comment]
This is a good idea. As background, I've actually been running a discrete fullnode on separate infra, but failed to do so for 64. Aside from testnets, it's important that we replicate this functionality for preview, so that we can catch bugs like https://github.com/penumbra-zone/penumbra/pull/3650 before release. However, it's complicated in that we must preserve the contents of the ACME cache, currently defined as `<pd_home>/rustls_acme_cache`: https://github.com/penumbra-zone/penumbra/blob/v0.64.2/crates/bin/pd/src/main.rs#L487-L488 Most of our preview logic is a full wipe and reset, and we'll need to be a bit more careful to avoid getting a domain banned from the ACME ratelimits.

**Comment by conorsch** [comment]
Added a workflow for this on preview. I'm going to run it ad-hoc a few times, and if no problems—like ratelimit triggers—then I'll move it to prod ACME API and make it part of the automatic deployments.

**Comment by conorsch** [comment]
The automatic preview deploy is triggering too early, before the newly created network's RPC endpoints are returning. For most of our deploys, that's not a problem, because they'll automatically retry until successful. For the "standalone" config, however, that doesn't leverage the same orchestration, we need to be more explicit. 

Two improvements come to mind: ensure that the RPC endpoints are honoring the readiness state of the fullnodes behind them: right now, any fullnode in the deployment is instantly added to the RPC backend pool, but we should gate admission into the pool on formal readiness, meaning the internal rpc endpoint is returning OK. We could also instruct the deploy flow to block until all pods are ready, which would resolve the problem of the standalone deploy firing too early, but not address the intermittent RPC downtime during chain resets on preview.

**Comment by conorsch** [comment]
This work is basically complete, although I haven't documented the new endpoints anywhere. I'll stick those in the wiki before closing. 

One major omission is that we don't have automatic handling of point-releases for these standalone nodes. That's fine: we're more focused on upgrades right now (#4087), which requires a lot of manual maintenance. Will circle back with a more automated setup for point releases when there's time, otherwise I'll handle that manually for the next few point releases.

**Comment by conorsch** [comment]
This work is done. We now have a standalone node, serving `pd` directly, exercising its auto-https logic, for both testnet and preview:

* https://solo-pd.testnet.plinfra.net/
* https://solo-pd.testnet-preview.plinfra.net/

Using a separate domain as a precaution to avoid banning cert issuance on the for-now more commonly used domain, `penumbra.zone`. There are some shortcuts here: we don't ingest metrics from these hosts, point-releases don't roll out to them automatically. They're SSH-accessible to the PL team, so they also serve as "always-on" boxes. One change I haven't yet made that I'd very much like to is an optional flag to store the acme cert info in a separate directory, which would vastly simplify using the https logic for pd in a lot more cases. 

The broad strokes of work described here is accomplished, so I'm closing the ticket.
