### ISSUE TITLE
Add pretty-printing method for TransactionPlan

### ISSUE THREAD

**Issue by cronokirby** [penumbra-zone/penumbra#3444]
Right now, there's no good way to display a transaction plan in a pretty-printed and easily-understandable human format.

Doing this will be useful for threshold custody.

One way to do this is by printing the JSON representation; I do not believe this is satisfactory:

- JSON adds extra cruft to such a display, even when pretty printed.
- Some items are formatted differently than we're used to, such as addresses.

I propose adding an explicit method to the plan to accomplish this, or to add a Display impl for this purpose.

**Comment by hdevalence** [comment]
This can't be a Display impl, because properly interpreting the plan requires at least an FVK (how do you understand which addresses are yours?), and also trusted asset metadata (how do you know what denom units are correct?).

That said, we should use JSON for now. There is no user-facing software that needs a pretty terminal printout of the transaction plan. We can wait to do this until after implementing the real version of this feature in the browser extension.

**Comment by redshiftzero** [comment]
Right now for threshold signing, many important fields for the signer to inspect - e.g. the address, asset ID - are effectively unintelligible, so we'll need to pick this up soon

**Comment by hdevalence** [comment]
To do this, we could adopt a similar strategy as we used in Prax: transforming the TransactionPlan into a stub TransactionView, then using the TransactionView rendering logic we already have.

**Comment by cratelyn** [comment]
i have tagged this as `needs-refinement` so that we can talk about & prioritize this at the next backlog grooming.
