### ISSUE TITLE
Add missing-docs warning to penumbra crates

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#345]
This will help us to document things closer in time to the time when they are created.

**Comment by hdevalence** [comment]
We might want to wait to do this until we have less churn in the codebase -- I'm not sure it's always better to document things closer in time to when they are created, since if we rapidly iterate on some code, we might end up spending a lot of time documenting code that we later reshape or remove.

Another consideration is about the quality of documentation: if we require docs on every public item, we might encourage filling in some minimal stub documentation to remove the warning, which removes our ability to automatically determine whether or not something is actually documented.
