### ISSUE TITLE
Serialization round-trip fuzzing and snapshot testing

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#351]
It would be good to have some tests that assure us that we are serializing and deserializing correctly. There are two kinds of tests that I can see being particularly useful:

1. property-based tests for each serialized type checking that `serialize; deserialize` is the identity
2. snapshot testing to ensure that serialization formats don't change unintentionally

## Roundtrip serialization fuzzing

I suggest we use the [`proptest`](https://docs.rs/proptest/latest/proptest/index.html) library to create property-based tests that check serialization round-tripping through each serialization format we want to support (presently, that's `serde_json` and `bincode`, I believe).

We can define a macro to generate these tests, since they are likely to be quite formulaic. I would like to be able to say something like:

```rust
use penumbra_crypto::*;
proptest_serialization_roundtrip![Address, NoteCommitment, AssetId, Denom, Value];
```

This should generate code that invokes the proptest harness, relying on `Arbitrary` instances for each type. A separate test function should be created for each type, rather than one big test function, because this will enable more fine-grained error reporting in the `cargo test` view (as well as parallel test execution).

## Snapshot testing

In addition to ensuring serialization is sensible *now*, we would like to ensure that it is sensible with respect to the past. Snapshot testing is the mechanism I propose to deal with this, specifically the [`insta`](https://insta.rs/) crate. This allows you to check in files to the repository which represent a "correct" output of the test, and if the expected value changes, you must update the contents of the snapshot file.

Similarly to the serialization round-trip checking, we should be able to make this succinct by writing macros to generate such tests from a list of type names.

Implementing this kind of testing would ensure that we don't accidentally break wallet serialization, or more seriously, break the serialization used by the various hash-based structures. We could additionally use snapshot testing to ensure that the `CryptoHash` implementations for things stored in the merkle trees do not get altered without an intentional acknowledgement of this change.

**Comment by hdevalence** [comment]
For roundtrip serialization testing, I think it would make sense for the macro to be defined in the `penumbra-proto` crate, and to require that the type be `Protobuf`, so that we can't use it except on types for which we've explicitly defined serializations (since we now do that via `.proto` files).

Because of our decision to base all of the serialization around protos, I'm less concerned about snapshot testing -- we check in all of the protos, and we fully determine the Serde implementations from the protos plus the "shaping" annotations, so we know that we can't accidentally break serialization, because that would require explicit changes to the data formats.
