### ISSUE TITLE
pcli cannot deserialize AppParameters from testnet-preview

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/penumbra#3716]
**Describe the bug**
pcli cannot deserialize AppParameters from testnet-preview

**To Reproduce**
1. `git checkout main`
2. `PENUMBRA_NODE_PD_URL="https://grpc.testnet-preview.penumbra.zone/" cargo run --release --bin pcli v list-tx-hashes`
3. see error

**Expected behavior**
pcli should be able to interact with grpc

**Screenshots**

<img width="1028" alt="Screenshot 2024-01-31 at 15 46 56" src="https://github.com/penumbra-zone/web/assets/134443988/62d0bb86-a6cb-4066-ae42-8dfd2f184289">

**Additional context**
web clients are also unable to deserialize https://github.com/penumbra-zone/web/pull/443

<img width="1282" alt="Screenshot 2024-01-31 at 15 15 31" src="https://github.com/penumbra-zone/web/assets/134443988/54d10bcf-7895-44ed-b503-6271cb60edeb">

**Comment by conorsch** [comment]
FYI preview deploys were stuck today: 

![preview-deploys-stuck](https://github.com/penumbra-zone/penumbra/assets/657862/3b32e6f4-a0c4-4e9c-b71a-89fcf29aba07)

As of https://github.com/penumbra-zone/penumbra/pull/3717 that should be resolved, and we'll correctly be serving latest `main` again. However, at a glance I expect the problem to persist, because the intervening PRs don't seem to touch the logic in question. Will test after latest deploy finishes and confirm.

**Comment by conorsch** [comment]
Indeed, still a problem:

```
❯ cargo run --release --bin pcli -- --home ~/.local/share/pcli-preview view sync
    Finished release [optimized] target(s) in 0.26s
     Running `target/release/pcli --home /home/conor/.local/share/pcli-preview view sync`
Error: status: Internal, message: "protocol error: received message with invalid compression flag: 52 (valid flags are 0 and 1) while receiving response with status: 404 Not Found", details: [], metadata: MetadataMap { headers: {"content-type": "text/plain; charset=utf-8", "x-content-type-options": "nosniff", "content-length": "19", "date": "Thu, 01 Feb 2024 00:14:20 GMT"} }

❯ git rev-parse HEAD
66b13e98643b8af8285238c62657ded81e8824f1
```

We can rule out these PRs as the cause of the problem:

* https://github.com/penumbra-zone/penumbra/pull/3711
* https://github.com/penumbra-zone/penumbra/pull/3714
* https://github.com/penumbra-zone/penumbra/pull/3715
* https://github.com/penumbra-zone/penumbra/pull/3703

because they hadn't been deployed at the time this issue was reported. 

*

**Comment by turbocrime** [comment]
it seems to be working for me, now.

**Comment by erwanor** [comment]
`status: 404 Not Found` - I think you're window manager setup made you so fast you frontran the deployment

**Comment by conorsch** [comment]
For me too:

```
❯ cargo run --release --bin pcli -- --home ~/.local/share/pcli-preview view balance
    Finished release [optimized] target(s) in 0.27s
     Running `target/release/pcli --home /home/conor/.local/share/pcli-preview view balance`
Scanning blocks from last sync height 72 to latest height 72
[0s] ██████████████████████████████████████████████████       0/0       0/s ETA: 0s
 Account  Amount          
 # 0      20000gm         
 # 0      500000test_usd  
 # 0      100cube         
 # 0      10000pizza      
 # 0      1000000penumbra 
 # 0      20000gn         
```

I think I hadn't waited long enough for the public endpoints to update. I'll think more about how we can catch this more proactively: we should have `pcli view sync` pass post-deploy at the least.

**Comment by turbocrime** [comment]
thanks!
