### ISSUE TITLE
`pcli` should be using `TransactionPlannerRequest`

### ISSUE THREAD

**Issue by jessepinho** [penumbra-zone/penumbra#3724]
**Describe the bug**
I was just working on https://github.com/penumbra-zone/web/issues/309, and I noticed that `TransactionPlannerRequest` doesn't include a `feeTier` property. (This issue is addressed in #3722.)

I was pairing with @grod220 on adding that property when we realized that, if `feeTier` is missing from `TransactionPlannerRequest`, but fee tiers are _supported_ in `pcli`, then `pcli` must not be using a `TransactionPlannerRequest` when planning transactions. And indeed that appears to be the case: `pcli` [calls `planner.set_fee_tier` directly](https://github.com/penumbra-zone/penumbra/blob/jessepinho/fee-tier-support-in-transaction-planner-request/crates/bin/pcli/src/command/tx.rs#L362-L364) rather than constructing a `TransactionPlannerRequest` that includes the fee tier.

I may be wrong about this, but it seems that `pcli` should essentially be a dumb client that acts just like the web extension — i.e., it should be exercising every `*Request` that core defines, since it's core's first client. That is, whenever there's a breaking change in core, `pcli` should _always_ break. But if `pcli` isn't using all the different `*Request` methods core defines, no one will know when there's a breaking change in core.

I'm probably using some incorrect terminology here, so I hope this makes sense. Feel free to follow up with any questions/disagreements/etc.

**Solution**
Ensure that `pcli` is using every interface that core provides, so that we know that the API contract core exposes is working as expected.

**Comment by grod220** [comment]
That's interesting. It seems that the web extension is the sole view service implementation then? I think it would be helpful if pcli issued view service requests internally so issues with the rpc methods would be more evident from the core repo.

**Comment by hdevalence** [comment]
Correct, pcli and other Rust software don't use the TransactionPlannerRequest, because it's a worse and less expressive RPC wrapper around the Planner API. We shouldn't change this — it would make the Rust code worse — and instead we should continue to use the web use case to drive and discover requirements for the RPC.

**Comment by jessepinho** [comment]
OK — if that's by design, I'll close this ticket.

**Comment by hdevalence** [comment]
Yep — to put it another way, planning and building transactions isn't really rhetorical responsibility of the view service, whose job is to scan and index data visible with a given viewing key. But since planning and building transactions requires Rust code, it's convenient for the view server to expose that for clients that can't do that themselves. Inside Rust code, there's no reason not to just import the libraries.
