### ISSUE TITLE
How to View Private key generated in Pcli - Need commands.

### ISSUE THREAD

**Issue by karna0730** [penumbra-zone/penumbra#3727]
** I have Generated New wallet with Private keys  How to View That again  or how to export the Private key into afile **

Below commands are being addressed in the guide 
Need pcli Commands for following ...
pcli init soft-kms generate  -         to generate a new private keys
pcli view address 0   -              to check address

Can you please help in how to check this?

To View Private key generated ---    ?????

**Comment by conorsch** [comment]
When `pcli` generates new key material, it writes it a file on the local machine and displays that path to the user, e.g. :

```
$ pcli init soft-kms generate
YOUR PRIVATE SEED PHRASE:
[SEED PHRASE]
Save this in a safe place!
DO NOT SHARE WITH ANYONE!
Writing generated configs to [PATH TO PCLI DATA]
```


This behavior is [documented in the guide](https://guide.penumbra.zone/main/pcli/wallet.html). You can inspect that TOML file and view both the SpendKey and the FullViewingKey. It's more important, however, to ensure you've backed up your seed phrase, so that you can import it again in the future if needed. It's not possible to view the seed phrase after it's been displayed.

**Comment by conorsch** [comment]
In the future, please ask support questions like this in our Discord, rather than opening issues on Github. You can find a link to our Discord also in the guide: https://guide.penumbra.zone/main/resources.html
