### ISSUE TITLE
tests: 👪 support for multiple validators in mock consensus engine

### ISSUE THREAD

**Issue by cratelyn** [penumbra-zone/penumbra#3760]
stub issue.

see #3588.

eventually, **not as part of the initial MVP effort**, we should implement the ability to run multiple "nodes" with the mock consensus engine.

this will likely be needed to give us assurance about some of our chain components.

**Comment by hdevalence** [comment]
I feel pretty strongly that we should not plan to do this, because it is a layering violation. 

The state of the Penumbra application only depends on the messages delivered to it from its consensus engine. It does not know anything about the network. So there is no need to simulate consensus. We only need to be able to mock the messages delivered to the application, network issues are exactly the complexity we don't want in the test suite.
