### ISSUE TITLE
Testnet Guide 

### ISSUE THREAD

**Issue by Whizzy6868** [penumbra-zone/penumbra#3791]
This is my little contribution to the community

Testnet guide simplified 

link: https://github.com/Whizzy6868/Penumbra-Testnet.git

Get started on Penumbra

**Comment by conorsch** [comment]
Thanks for sharing. See also https://github.com/penumbra-zone/penumbra/issues/4186, in which we discuss whether to provide comprehensive scripting like this as part of the core monorepo. For now, I'm biased against it, for reasons explained in 4186. Discussion of these types of guides would be welcome in the Discord, so that others can make use of the resources. Since there's no problem being reported here, I'm closing this issue.
