### ISSUE TITLE
tests: ⭐ mock consensus can `InitChain` with a single validator

### ISSUE THREAD

**Issue by cratelyn** [penumbra-zone/penumbra#3816]
see #3588.

with #3787 complete, we can proceed to the next phase of work on the mock consensus testing framework: we should implement the logic to patch an `AppState` with the information for a single test validator.

see this todo comment: https://github.com/penumbra-zone/penumbra/blob/7d61991df55ad0039b433af237a8e2080ff65a34/crates/core/app/tests/common/mod.rs#L73-L77

**Comment by hdevalence** [comment]
One note: it's actually possible this might not be a blocker relative to block production. 

The reason we need to modify the genesis data to match the mock engine's validators (namely, defining corresponding penumbra validators and allocating delegation tokens at genesis) is that otherwise the staking component will have no validators, feed that back to Comet as an update, and Comet will halt rather than setting the validator set to the empty set.

But currently the mock engine doesn't do any validator set tracking anyways. So it seems possible that as long as we're not trying to test the staking component specifically, this isn't a blocker.
