### ISSUE TITLE
shielded-pool: dummy spends can grief nullifiers

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/penumbra#3859]
**Is your feature request related to a problem? Please describe.**
It is possible to mark arbitrary nullifiers as "spent" by creating a note with value 0. This will cause the `SpendCircuit` to treat it as a dummy spend which will lift make constraint check  to always pass ([should_enforce](https://github.com/penumbra-zone/penumbra/blob/efe8c79112416771db6f53c24ddeb68f97f77591/crates/core/component/shielded-pool/src/spend/proof.rs#L186-L187)). Since the stateful check pass, the action gets executed and the nullifier is marked as spent.

@hdevalence suggested that we modify the check to only skip the merkle integrity check if the note is a dummy spend.

Initial suggestion for how to fix this:

- [x] #3868
- [x] #3869

**Comment by redshiftzero** [comment]
Initial suggestion for how to fix this:
1. `SpendPlan::dummy()` should use valid data instead of random,
2. the circuit should only short-circuit on the merkle proof verification,
3. the rust code that corresponds to the circuit code should also check everything except for the merkle path,
4. we need to get a spend auth sig for this 0-valued spend.

**Comment by aubrika** [comment]
adding to Sprint 0 as unplanned work, targeted for 2/23

**Comment by avahowell** [comment]
The underlying issue is fixed as of #3871
