### ISSUE TITLE
Confirm chain id in `pcli` requests

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#394]
Currently, it's very possible to accidentally connect to the wrong chain with `pcli`, resulting in confusion (where are my assets? why has time gone backwards?). This should instead result in an error.

I can see 3 possible ways this could be implemented, depending on where the check occurs:

1. `pcli` transmits the id of the chain it expects to be connecting to in each request, and `pd` returns an error if that does not match the chain id of the chain `pd` is managing.
2. `pd` returns, along with any other result data, its chain id, and `pcli` checks this and returns an error instead of processing the rest of the result if it does not match the expected chain id.
3. `pcli` precedes each request other than `ChainParams` itself with a `ChainParams` request, and checks to make sure the chain id matches before proceeding.

**I think that (3) is the best solution, because:**

- unlike (1) it means that `pcli` doesn't ever disclose to `pd` what chain id it is expecting to see (which could leak local development information to a public server in the case of misconfiguration), and
- unlike (1) and (2) it means that this can be a transparent upgrade, because it does not change the proto types.

Aside from the changes mentioned in (3), implementing this will require a change to the wallet format to store the expected chain id. Considerations here:

- This field should be optional: when it is not yet populated (as in a wallet that pre-existed prior to this update), it should be filled in the first time a chain is contacted.
- When the wallet is initialized, it should also be left blank, and then only when the client connects to the chain should it be filled in, at this point effectively "locking" the client to that chain.
- `pcli wallet reset` should remove this field, so that keys can be reused across multiple chains by resetting all the rest of the state.

**Comment by hdevalence** [comment]
Since we store the `ChainParams` as part of the wallet state now, I don't think we have to do anything extra to record the expected chain ID.  But we do have to figure out how to handle the case where the chain parameters haven't been downloaded yet.

I think (3) is less preferable, because it means that clients have to do some extra network roundtrips, and have to figure out when it's appropriate to do the extra requests.  Instead, I'd suggest (1'):

1'. Add a `string chain_id` to every request proto, and have `pd` return an error if the string is nonempty and doesn't match the expected chain ID; if the string is empty or if the string matches, process the request as normal.

This is also drop-in compatible, since adding fields to protos is fine, as all proto fields are supposed to be optional by default.  It also gives the behavior we'd like for grabbing the chain params initially, acting as "pin on first use".
