### ISSUE TITLE
Check that all fees are burned, not just the base fee

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#4080]
**Is your feature request related to a problem? Please describe.**

The fee mechanism is designed to have a protocol-required base fee amount. Any fee above that amount is a proposer tip. However, to save complexity prior to mainnet, we should avoid implementing proposer tip distributions, and simply burn the entire fee. The intended behavior can be implemented in a later chain upgrade.

**Describe the solution you'd like**

Ensure that we burn the entire fee amount, so that validator distributions are not used.

**Comment by erwanor** [comment]
We don't do any tracking of proposer tips but the scaffolding to make this happen exists. It is tracked in #3633 and leans on the [distribution + funding] component stack, which should be memorialized in an ADR soon.

Since there's no protocol tracking of the tips, the entire fee amount is burned, even the part that is in excess of the base fee.
