### ISSUE TITLE
Derive `SpendSeed` from seed phrase

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/penumbra#419]
Our [`SpendSeed`](https://github.com/penumbra-zone/penumbra/blob/main/crypto/src/keys/spend.rs#L16) is currently generated randomly. We should instead derive the `SpendSeed` from a series of randomly generated words as described in [BIP39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki) since it's easier to remember English words. Users then just need to remember the seed phrase. This would require changes to `SpendKey::generate` in the crypto crate as well as changes to the `pcli wallet` commands (e.g. to `import` from a seed phrase instead of the spend seed). 

A recommended wordlist: https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt

**Comment by hdevalence** [comment]
Two things we should consider when doing this:

1. We should add an intermediate level of derivation, so that we can derive multiple spending authorities from a single seed.  (Use case: there's one viewing authority per spending authority, and it would be useful to allow the possibility of creating multiple viewing authorities from the same seed phrase).

2. We should ensure that the BIP32 derivation we do is compatible with what we'd need for ledger support.
