### ISSUE TITLE
Check that IBC handlers don't short-circuit misbehavior handling

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#4209]
**Describe the bug**

While discussing https://github.com/cosmos/ibc-go/issues/6159 , I mentioned our IBC implementation's short-circuit behavior, and @srdtrk pointed out that there's a possibility that this causes us to not handle misbehavior correctly:

> The reason why we don’t quit so early like penumbra is because we check if UpdateMsg actually is evidence of misbehavior. (The check should be done imo)

We should audit the code and ensure that our short-circuiting behavior doesn't prevent this.

A fix for this issue is either:

- An explanation of why we handle misbehavior correctly despite our short-circuiting (if this is the case)
- A fix to handle misbehavior correctly (if it was not correct)

**Comment by avahowell** [comment]
The short circuiting behavior for client updates will only short circuit in the event where we already have a header for the provided height, *and* the consensus state for that header is identical to the one contained in the update:

https://github.com/penumbra-zone/penumbra/blob/05366eb72523a91a1723ddbd47493403087a76d5/crates/core/component/ibc/src/component/msg_handler/update_client.rs#L186

So, if a relayer provides an equivocation to the update handler, `update_is_already_committed` will return false, and the rest of the update handler will continue to `next_tendermint_state` which will set the next state for the client as frozen due to the equivocation.

Closing this issue for now since I think this addresses the concern raised
