### ISSUE TITLE
`pcli` installation instructions don't have copy-pastable code for MacOS

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#4255]
**Describe the bug**

`pcli` is more difficult to install on MacOS because the instructions aren't copy-pastable: only Linux commands are provided.

It would be better if the guide had a separate block with copy-pastable MacOS instructions.

**Comment by conorsch** [comment]
Closely related to #4256. We can definitely provide copy/paste functionality. I'm testing newer versions of `cargo-dist` in a private fork, and there's an opt-in for generating a copy/pasteable one-liner that pulls down a shell script and installs ad-hoc. We don't need msi support, since Windows isn't an install target for us, so the single shell script should work well for both macos and linux. If not, we can still write our own copy/pastable docs, as we do already.
