### ISSUE TITLE
Dex: provide "candlestick" RPC

### ISSUE THREAD

**Issue by aubrika** [penumbra-zone/penumbra#4399]
In order to enable frontend support for price history / volume, we should provide an RPC endpoint for "candlestick" charts of price data.

**Comment by zbuc** [comment]
Questions:

Is the open price for a block the _first executed price_ during that block, or is it the _last executed price_ during the previous block?

Currently I'm only populating candlesticks via execution prices, and not doing any cross-block logic, it seems cleanest, but I'm not sure if it's correct.

i.e.
open price = first price executed during the block
close price = last price executed during the block

but this means that block N close price is not necessarily the same as block N + 1 open price

I'm also not sure what the API should do for blocks with no transactions for a trading pair -- should the API handle returning a new candlestick with the open/close/high/low set to the previous block's close or is it up to the client to stitch that together? Seems like maybe the API should do it.

**Comment by hdevalence** [comment]
I think pulling the last block's data, and, if it is present, using its end price as the start price would be reasonable. But not doing it would also be reasonable, and maybe easier. Since the candlestick data is in non verifiable storage we are not really committed either way, I think.

When there are no trades, it could be nice have the API give an empty candle. I'm not sure how we would do this without a DOS risk though. Creating positions is permissionless, on any pair, so someone can create lots of positions on new pairs they made up. If doing that causes empty candles to be generated forever that would be unfortunate. So I think we should not generate anything if there were no trades. The candlestick data has a height embedded so the client can load it into a map and see what's missing.

**Comment by zbuc** [comment]
The "not returning candlesticks if there's no volume" approach seems to have some prior examples like Polygon so that seems reasonable.

**Comment by zbuc** [comment]
This has been merged but the streaming RPC is currently disabled due to a potential DOS vector.
