### ISSUE TITLE
[bug] view service misses some swap and swap claim transactions when scanning (tendermint related)

### ISSUE THREAD

**Issue by Valentine1898** [penumbra-zone/penumbra#4465]
Initially we found that our wallet extension may not detect some swap or swap claim transactions https://github.com/penumbra-zone/web/issues/1003

While debugging, I realized that scanning the block for new swaps and notes works correctly, and the issue is that we just sometimes get an empty transaction list when querying `txsByHeight` (extension uses `QueryService.TransactionsByHeight` )

![image](https://github.com/penumbra-zone/penumbra/assets/25391690/975f121a-7c96-4791-a097-3bab45d995f0)

I later discovered that pcli can also miss some swap and swap claim transactions

![image](https://github.com/penumbra-zone/penumbra/assets/25391690/2460e1fa-44f6-4a76-a3c2-347d3bc12599)

It is important to note that extension can detect transactions that pcli has not detected (and vice versa)

![image](https://github.com/penumbra-zone/penumbra/assets/25391690/b6de24d5-9d3a-4a1b-88de-a27ec6ac6d35)

Also, if you run a `view reset`, you will be able to detect any transactions that were missed initially 

I was able to reproduce the bug 3 times for 100 transactions, so most likely you will have to send many swap transactions to reproduce it 

Also some of my thoughts:
- it does not matter whether pcli or extension sends the transaction 
- I think the bug depends on how early from the block generation time we request txsByHeight

**Comment by aubrika** [comment]
Theory proposed for investigation: this may be a race condition between `pd` notifying the client of the compact block and `pd` having correctly assembled the list of full transactions it would use to respond to client requests for full tx data - which would explain the behavior observed that this doesn't repeat following re-sync. If this is the case, we may need to accumulate the tx bytes and commit those on recording instead of re-requesting that data.

**Comment by cratelyn** [comment]
closing this, per https://github.com/penumbra-zone/penumbra/issues/4601#issuecomment-2186961948.

it's my understanding that this, along with the other issues linked there, are all symptomatic of the same issue, fixed in #4578 and #4586. if this behavior is still being observed on the latest version(s) of `penumbra-view`, please do not hesitate to re-open this!
