### ISSUE TITLE
A convenient way to query all open lp positions from pcli

### ISSUE THREAD

**Issue by masonyonkers** [penumbra-zone/penumbra#4825]
**Is your feature request related to a problem? Please describe.**
There is currently no easy way to view the status of all of a wallet's open liquidity positions from pcli.

**Describe the solution you'd like**
A subcommand that acts like _pcli query dex position plpid_ for all open positions in an account.

**Describe alternatives you've considered**
I am currently using a bash script that queries balance and runs _pcli query dex position plpid_ for each open position. This works for now, but is slow and not feasable if there are a large number of open positions. 

**Additional context**
N/A

**Comment by aubrika** [comment]
Thanks for opening this, I think it's a good idea. We'll add it to our queue. :)

**Comment by zbuc** [comment]
I agree that pcli should be changed to support displaying all positions at once.

@masonyonkers I do want to point out that depending on what you're trying to do you might be better off using the penumbra libraries from a Rust program instead of automating pcli with bash. You can see an example of it here: https://github.com/penumbra-zone/osiris
