### ISSUE TITLE
pindexer: crash on "out of range integral type conversion"

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#4906]
**Describe the bug**
A running instance of `pindexer` version `v0.80.7` recently crashed with error message:

```
Error: out of range integral type conversion attempted
```

After brief investigation, @cronokirby pointed to a possible underflow in how pindexer reconciles VCB events. Possible solutions are to enforce ordering in the emission of ABCI events, or just make pindexer more forgiving. We've already confirmed that total counts of the ins and outs of the dex in a pindexer database sum to 0, which is as expected, so any variation would happen with a single block and should be forgiven.

**Comment by cronokirby** [comment]
https://github.com/penumbra-zone/penumbra/blob/fcce6314cb3b72cfcf0361e0ea48f16291da150f/crates/bin/pindexer/src/supply.rs#L584 is there the issue is sourced from, and happens when this subtraction underflows, causing the value to not fit in a u64.

The reason this happens is because there's no guaranteed ordering between the debit and credit events of a block, so in particular the dex supply can "temporarily" be negative.
I've empirically confirmed that on mainnet, this value never stays negative by the end of a block, so this issue is purely an event processing related concern, and there's no indication that event emission has a bug in any way.

The simplest fix is probably just to allow this value in the supply app view to be negative, which shouldn't ever be observable unless currently processing the events for a given block.
