### ISSUE TITLE
Maybe we need cyclic component dependencies?

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#961]
Currently, as @zbuc points out, the staking crate depends on a lot of functionality of the shielded pool crate, to mint new notes, etc. But this means, because crates cannot be cyclic in dependency, that the shielded pool cannot depend on anything defined in the staking crate. This is a problem when implementing quarantining, as the rules for quarantining require querying the current state of validators, which is functionality defined (rightfully!) in the staking crate. This leads to a sadness.

Here are some ways out of the sadness:

1. We could replicate the shielded pool functionality needed in the staking crate (bad, lots to replicate).
2. We could replicate the staking functionality needed in the shielded pool crate (slightly less bad, just need to make a few queries, but we can't use any domain types).
3. We could move the domain types for the validator state and bonding state into a separate crate, upon which both shielded pool and staking depend.
4. We could move the required functionality of the shielded pool for the staking crate into a separate crate, upon which both shielded pool and staking depend (probably bad, not very sensible division of concerns).
5. We could scrap the idea of having separate crates for separation of component concerns, admit that cyclicity is necessary to enable code reuse when components need to refer to each others' states, and enforce modularity with modules rather than crates, in one big component crate with submodules.

Of these, I think that (5) is likely the best solution, especially because we'll likely end up needing to do more (1..=4) style hacks as we add more components. However, the downside of (5) is that it conflicts with everything else that is in flight, because it requires refactoring all of the components simultaneously. Perhaps this should happen over the weekend (I volunteer as tribute).

This is a blocker for #960, which is the very-in-progress work on #588.

**Comment by hdevalence** [comment]
If we do (5), where should we put all of the components?  

One option would be to have a crate that depends on the current `component` crate and has all of the component implementations.  Another option would be to use the `component` crate itself; we could have `::shielded_pool`, `::stake`, `::ibc` modules with the current contents of those crates.

Another point to consider is whether this is an opportunity to repair some of the awkwardness with the `transaction` crate, which uses only the _proto_ versions of some types rather than the domain types, to work around this kind of cyclicity issue.  On the other hand, perhaps it's better to keep the `transaction` code separate, so that, e.g., a custody service doesn't need to import the entire application, just to be able to compute auth hashes of a transaction plan (e.g., if we wanted to compile that code to wasm to run in a browser extension).

Whatever we do could probably also solve #927 at the same time.

**Comment by plaidfinch** [comment]
I think using the current component crate would be sensible (your latter option). I agree that keeping the transaction code in a separate crate is good, especially because wasm compilation may not be able to handle all of `pd`, but it could likely handle whatever's in there. Do you think that resolving #927 would look like putting it in the `component` crate, per this plan?
