### ISSUE TITLE
Add await-nullifier functionality to the view service

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/penumbra#999]
@hdevalence proposes:

```protobuf
rpc NullifierStatus(NullifierStatusRequest) returns (NullifierStatusResponse);

message NullifierStatusRequest {
  crypto.FullViewingKeyHash fvk_hash = 1;
  crypto.Nullifier nullifier =2;
  bool keep_alive = 3;
}

message NullifierStatusResponse {
  bool spent = 1;
}
```

> idea being that if keep_alive is present, the connection stays open until it becomes spent

With quarantining implemented, we may also want to add an option to watch for a nullifier being rolled back, or to watch for it only once it is finally confirmed, rather than provisionally added to the quarantined nullifier set.

**Comment by hdevalence** [comment]
Once this API exists, we should change `pcli`'s `submit_transaction` to wait for confirmation of spends.  This is better than waiting for confirmation of outputs, because:

- The reason to wait for confirmation at all is to prevent accidental double-spends;
- All transactions worth confirming have spends, but not all of them have self-addressed outputs.
